SELECT [ID], [EQUIPMENT_NAME], [EQUIPMENT_TYPE], [LAST_MAINTENANCE_DATE] 
FROM [PROCESS_EQUIPMENTS] 
WHERE [IsDeleted] = 0 
	AND [IS_ACTIVE] = @PRM_PROCESS_EQUIPMENTS_IS_ACTIVE 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 