//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo-kahve.Common.Models; using  QuickCode . Demo
-kahve.ProductionModuleModule.Domain.Entities; using  QuickCode . Demo
-kahve.ProductionModuleModule.Application.Interfaces.Repositories; using  System . Threading . Tasks ;  using  Dapper ;  using  Microsoft . EntityFrameworkCore ;  using  Microsoft . Extensions . Logging ;  using  QuickCode . Demo
-kahve.Common; using  QuickCode . Demo
-kahve.Common.Extensions; using  QuickCode . Demo
-kahve.ProductionModuleModule.Persistence.Contexts; using  QuickCode . Demo
-kahve.ProductionModuleModule.Application.Dtos.CoffeeBean; using  QuickCode . Demo
-kahve.ProductionModuleModule.Application.Mappings; using  QuickCode . Demo
-kahve.ProductionModuleModule.Domain.Enums;
namespace QuickCode.Demo - kahve . ProductionModuleModule . Persistence . Repositories {
    public partial class CoffeeBeanRepository : BaseRepository, ICoffeeBeanRepository
    {
        private readonly WriteDbContext _writeContext;
        private readonly ReadDbContext _readContext;
        public CoffeeBeanRepository(ILogger<CoffeeBeanRepository> logger, WriteDbContext writeContext, ReadDbContext readContext) : base(logger, "CoffeeBean")
        {
            _writeContext = writeContext;
            _readContext = readContext;
        }

        public async Task<RepoResponse<CoffeeBeanDto>> InsertAsync(CoffeeBeanDto value)
        {
            return await ExecuteWithExceptionHandling("Insert", async () =>
            {
                var entity = value.ToEntity();
                await _writeContext.CoffeeBean.AddAsync(entity);
                await _writeContext.SaveChangesAsync();
                var resultDto = entity.ToDto();
                return new RepoResponse<CoffeeBeanDto>(resultDto, "Success");
            });
        }

        public async Task<RepoResponse<bool>> UpdateAsync(CoffeeBeanDto value)
        {
            return await ExecuteWithExceptionHandling("Update", async () =>
            {
                _writeContext.Set<Domain.Entities.CoffeeBean>().Update(value.ToEntity());
                await _writeContext.SaveChangesAsync();
                return new RepoResponse<bool>(true, "Success");
            });
        }

        public async Task<RepoResponse<bool>> DeleteAsync(CoffeeBeanDto value)
        {
            return await ExecuteWithExceptionHandling("Delete", async () =>
            {
                _writeContext.CoffeeBean.Remove(value.ToEntity());
                await _writeContext.SaveChangesAsync();
                return new RepoResponse<bool>(true, "Success");
            });
        }

        public async Task<RepoResponse<CoffeeBeanDto>> GetByPkAsync(int id)
        {
            return await ExecuteWithExceptionHandling("GetByPk", async () =>
            {
                var result =
                    from coffee_bean in _readContext.CoffeeBean
                    where coffee_bean.Id.Equals(id)
                    select coffee_bean;
                var response = await result.FirstOrDefaultAsync();
                return response == null ? new RepoResponse<CoffeeBeanDto>
                {
                    Code = 404,
                    Message = "Not found in CoffeeBean"
                }

                : new RepoResponse<CoffeeBeanDto>(response.ToDto(), "Success");
            });
        }

        public async Task<RepoResponse<List<CoffeeBeanDto>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            return await ExecuteWithExceptionHandling("Select", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<CoffeeBeanDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }

                var query = _readContext.CoffeeBean.OrderBy(o => o.Id).AsQueryable();
                if (pageNumber.HasValue && pageSize.HasValue)
                {
                    query = ApplyPagination(query, pageNumber.Value, pageSize.Value);
                }

                var result = await query.ToListAsync();
                return new RepoResponse<List<CoffeeBeanDto>>(result.ToDto(), "Success");
            });
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            return await ExecuteWithExceptionHandling("Count", async () =>
            {
                return new RepoResponse<int>(await _readContext.CoffeeBean.CountAsync(), "Success");
            });
        }
    }
}