//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo-kahve.Common.Models; using  QuickCode . Demo
-kahve.ProductionModuleModule.Domain.Entities; using  QuickCode . Demo
-kahve.ProductionModuleModule.Application.Interfaces.Repositories; using  System . Threading . Tasks ;  using  Dapper ;  using  Microsoft . EntityFrameworkCore ;  using  Microsoft . Extensions . Logging ;  using  QuickCode . Demo
-kahve.Common; using  QuickCode . Demo
-kahve.Common.Extensions; using  QuickCode . Demo
-kahve.Common.Helpers; using  QuickCode . Demo
-kahve.ProductionModuleModule.Persistence.Contexts; using  QuickCode . Demo
-kahve.ProductionModuleModule.Application.Dtos.CoffeeBean; using  QuickCode . Demo
-kahve.ProductionModuleModule.Application.Mappings; using  QuickCode . Demo
-kahve.ProductionModuleModule.Persistence.Sql; using  QuickCode . Demo
-kahve.ProductionModuleModule.Domain.Enums;
namespace QuickCode.Demo - kahve . ProductionModuleModule . Persistence . Repositories {
    public partial class CoffeeBeanRepository : BaseRepository, ICoffeeBeanRepository
    {
        public async Task<RepoResponse<List<GetByOriginResponseDto>>> GetByOriginAsync(string coffeeBeansOrigin, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetByOrigin", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByOriginResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.CoffeeBean.Query.GetByOrigin);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_COFFEE_BEANS_ORIGIN = coffeeBeansOrigin,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetByOriginResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in CoffeeBean");
                }
            });
        }

        public async Task<RepoResponse<List<GetByBatchIdResponseDto>>> GetByBatchIdAsync(string coffeeBeansBatchId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetByBatchId", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByBatchIdResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.CoffeeBean.Query.GetByBatchId);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_COFFEE_BEANS_BATCH_ID = coffeeBeansBatchId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetByBatchIdResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in CoffeeBean");
                }
            });
        }

        public async Task<RepoResponse<long>> GetTotalWeightAsync()
        {
            return await ExecuteWithExceptionHandling("GetTotalWeight", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CoffeeBean.Query.GetTotalWeight);
                var parameters = new
                {
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var result = await connection.ExecuteScalarAsync<long>(sql, parameters);
                return new RepoResponse<long>(result, "Success");
            });
        }

        public async Task<RepoResponse<List<GetRoastingProcessesForCoffeeBeansResponseDto>>> GetRoastingProcessesForCoffeeBeansAsync(int coffeeBeansId)
        {
            return await ExecuteWithExceptionHandling("GetRoastingProcessesForCoffeeBeans", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CoffeeBean.Query.GetRoastingProcessesForCoffeeBeans);
                var parameters = new
                {
                    PRM_COFFEE_BEANS_ID = coffeeBeansId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetRoastingProcessesForCoffeeBeansResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in CoffeeBean");
            });
        }

        public async Task<RepoResponse<GetRoastingProcessesForCoffeeBeansResponseDto>> GetRoastingProcessesForCoffeeBeansDetailsAsync(int coffeeBeansId, int roastingProcessesId)
        {
            return await ExecuteWithExceptionHandling("GetRoastingProcessesForCoffeeBeansDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.CoffeeBean.Query.GetRoastingProcessesForCoffeeBeansDetails);
                var parameters = new
                {
                    PRM_ROASTING_PROCESSES_ID = roastingProcessesId,
                    PRM_COFFEE_BEANS_ID = coffeeBeansId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetRoastingProcessesForCoffeeBeansResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in CoffeeBean");
            });
        }
    }
}