//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo-kahve.Common.Models; using  QuickCode . Demo
-kahve.ProductionModuleModule.Domain.Entities; using  QuickCode . Demo
-kahve.ProductionModuleModule.Application.Dtos.CoffeeBean; using  System . Threading . Tasks ;  using  QuickCode . Demo
-kahve.ProductionModuleModule.Domain.Enums;
namespace QuickCode.Demo - kahve . ProductionModuleModule . Application . Interfaces . Repositories {
    public partial interface ICoffeeBeanRepository : IBaseRepository<CoffeeBeanDto>
    {
        Task<RepoResponse<CoffeeBeanDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetByOriginResponseDto>>> GetByOriginAsync(string coffeeBeansOrigin, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetByBatchIdResponseDto>>> GetByBatchIdAsync(string coffeeBeansBatchId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<long>> GetTotalWeightAsync();
        Task<RepoResponse<List<GetRoastingProcessesForCoffeeBeansResponseDto>>> GetRoastingProcessesForCoffeeBeansAsync(int coffeeBeansId);
        Task<RepoResponse<GetRoastingProcessesForCoffeeBeansResponseDto>> GetRoastingProcessesForCoffeeBeansDetailsAsync(int coffeeBeansId, int roastingProcessesId);
        Task<RepoResponse<int>> UpdateWeightAsync(int coffeeBeansId, UpdateWeightRequestDto updateRequest);
    }
}