//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo-kahve.Common.Models; using  QuickCode . Demo
-kahve.ProductionModuleModule.Domain.Entities; using  QuickCode . Demo
-kahve.ProductionModuleModule.Application.Dtos.GrindingProcess; using  System . Threading . Tasks ;  using  QuickCode . Demo
-kahve.ProductionModuleModule.Domain.Enums;
namespace QuickCode.Demo - kahve . ProductionModuleModule . Application . Interfaces . Repositories {
    public partial interface IGrindingProcessRepository : IBaseRepository<GrindingProcessDto>
    {
        Task<RepoResponse<GrindingProcessDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetByRoastingProcessIdResponseDto>>> GetByRoastingProcessIdAsync(int grindingProcessesRoastingProcessId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetByStatusResponseDto>>> GetByStatusAsync(ProcessStatus grindingProcessesProcessStatus, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetPackagingProcessesForGrindingProcessesResponseDto>>> GetPackagingProcessesForGrindingProcessesAsync(int grindingProcessesId);
        Task<RepoResponse<GetPackagingProcessesForGrindingProcessesResponseDto>> GetPackagingProcessesForGrindingProcessesDetailsAsync(int grindingProcessesId, int packagingProcessesId);
        Task<RepoResponse<int>> UpdateStatusAsync(int grindingProcessesId, UpdateStatusRequestDto updateRequest);
    }
}