//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo-kahve.Common.Models; using  QuickCode . Demo
-kahve.ProductionModuleModule.Domain.Entities; using  QuickCode . Demo
-kahve.ProductionModuleModule.Application.Dtos.PackagingProcess; using  System . Threading . Tasks ;  using  QuickCode . Demo
-kahve.ProductionModuleModule.Domain.Enums;
namespace QuickCode.Demo - kahve . ProductionModuleModule . Application . Interfaces . Repositories {
    public partial interface IPackagingProcessRepository : IBaseRepository<PackagingProcessDto>
    {
        Task<RepoResponse<PackagingProcessDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetByGrindingProcessIdResponseDto>>> GetByGrindingProcessIdAsync(int packagingProcessesGrindingProcessId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetByStatusResponseDto>>> GetByStatusAsync(ProcessStatus packagingProcessesProcessStatus, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<int>> UpdateStatusAsync(int packagingProcessesId, UpdateStatusRequestDto updateRequest);
    }
}