//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo-kahve.Common.Models; using  QuickCode . Demo
-kahve.ProductionModuleModule.Domain.Entities; using  QuickCode . Demo
-kahve.ProductionModuleModule.Application.Dtos.ProcessEquipment; using  System . Threading . Tasks ;  using  QuickCode . Demo
-kahve.ProductionModuleModule.Domain.Enums;
namespace QuickCode.Demo - kahve . ProductionModuleModule . Application . Interfaces . Repositories {
    public partial interface IProcessEquipmentRepository : IBaseRepository<ProcessEquipmentDto>
    {
        Task<RepoResponse<ProcessEquipmentDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetActiveResponseDto>>> GetActiveAsync(bool processEquipmentsIsActive, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<int>> DeactivateAsync(int processEquipmentsId, DeactivateRequestDto updateRequest);
    }
}