SELECT [ID], [NOTE_TEXT], [CREATED_DATE] 
FROM [RECIPE_NOTES] 
WHERE [IsDeleted] = 0 
	AND [RECIPE_ID] = @PRM_RECIPE_NOTES_RECIPE_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 