SELECT [ID], [ROASTING_PROCESS_ID], [GRINDING_DATE], [GRIND_SIZE], [PROCESS_STATUS] 
FROM [GRINDING_PROCESSES] 
WHERE [IsDeleted] = 0 
	AND [ROASTING_PROCESS_ID] = @PRM_GRINDING_PROCESSES_ROASTING_PROCESS_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 