SELECT [ID], [ROASTING_PROCESS_ID], [GRINDING_DATE], [GRIND_SIZE], [PROCESS_STATUS] 
FROM [GRINDING_PROCESSES] 
WHERE [IsDeleted] = 0 
	AND [PROCESS_STATUS] = @PRM_GRINDING_PROCESSES_PROCESS_STATUS 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 