SELECT PP.[ID], PP.[GRINDING_PROCESS_ID], PP.[PACKAGING_DATE], PP.[PACKAGE_SIZE_GRAMS], PP.[PROCESS_STATUS], PP.[CREATED_DATE] 
FROM [PACKAGING_PROCESSES] PP 
	INNER JOIN [GRINDING_PROCESSES] GP 
			ON PP.[GRINDING_PROCESS_ID] = GP.[ID] 
WHERE PP.[IsDeleted] = 0 
	AND GP.[IsDeleted] = 0 
	AND PP.[ID] = @PRM_PACKAGING_PROCESSES_ID 
	AND GP.[ID] = @PRM_GRINDING_PROCESSES_ID 
ORDER BY PP.[ID] 