SELECT GP.[ID], GP.[ROASTING_PROCESS_ID], GP.[GRINDING_DATE], GP.[GRIND_SIZE], GP.[PROCESS_STATUS], GP.[CREATED_DATE] 
FROM [PACKAGING_PROCESSES] PP 
	INNER JOIN [GRINDING_PROCESSES] GP 
			ON PP.[GRINDING_PROCESS_ID] = GP.[ID] 
WHERE PP.[IsDeleted] = 0 
	AND GP.[IsDeleted] = 0 
	AND GP.[ID] = @PRM_GRINDING_PROCESSES_ID 
ORDER BY GP.[ID] 