SELECT R.[ID], R.[RECIPE_NAME], R.[DESCRIPTION], R.[INSTRUCTIONS], R.[CREATED_DATE], R.[IS_ACTIVE] 
FROM [RECIPE_INGREDIENTS] RI 
	INNER JOIN [RECIPES] R 
			ON RI.[RECIPE_ID] = R.[ID] 
WHERE RI.[IsDeleted] = 0 
	AND R.[IsDeleted] = 0 
	AND R.[ID] = @PRM_RECIPES_ID 
ORDER BY R.[ID] 