SELECT R.[ID], R.[RECIPE_NAME], R.[DESCRIPTION], R.[INSTRUCTIONS], R.[CREATED_DATE], R.[IS_ACTIVE] 
FROM [RECIPE_CATEGORY_ASSIGNMENTS] RCA 
	INNER JOIN [RECIPES] R 
			ON RCA.[RECIPE_ID] = R.[ID] 
WHERE RCA.[IsDeleted] = 0 
	AND R.[IsDeleted] = 0 
	AND R.[ID] = @PRM_RECIPES_ID 
ORDER BY R.[ID] 