SELECT RN.[ID], RN.[RECIPE_ID], RN.[NOTE_TEXT], RN.[CREATED_DATE] 
FROM [RECIPE_NOTES] RN 
	INNER JOIN [RECIPES] R 
			ON RN.[RECIPE_ID] = R.[ID] 
WHERE RN.[IsDeleted] = 0 
	AND R.[IsDeleted] = 0 
	AND RN.[ID] = @PRM_RECIPE_NOTES_ID 
	AND R.[ID] = @PRM_RECIPES_ID 
ORDER BY RN.[ID] 