SELECT RCA.[ID], RCA.[RECIPE_ID], RCA.[CATEGORY_ID] 
FROM [RECIPE_CATEGORY_ASSIGNMENTS] RCA 
	INNER JOIN [RECIPES] R 
			ON RCA.[RECIPE_ID] = R.[ID] 
WHERE RCA.[IsDeleted] = 0 
	AND R.[IsDeleted] = 0 
	AND RCA.[ID] = @PRM_RECIPE_CATEGORY_ASSIGNMENTS_ID 
	AND R.[ID] = @PRM_RECIPES_ID 
ORDER BY RCA.[ID] 