SELECT RE.[ID], RE.[RECIPE_ID], RE.[EQUIPMENT_NAME], RE.[EQUIPMENT_DESCRIPTION] 
FROM [RECIPE_EQUIPMENTS] RE 
	INNER JOIN [RECIPES] R 
			ON RE.[RECIPE_ID] = R.[ID] 
WHERE RE.[IsDeleted] = 0 
	AND R.[IsDeleted] = 0 
	AND RE.[ID] = @PRM_RECIPE_EQUIPMENTS_ID 
	AND R.[ID] = @PRM_RECIPES_ID 
ORDER BY RE.[ID] 