SELECT RI.[ID], RI.[RECIPE_ID], RI.[IMAGE_URL], RI.[DESCRIPTION] 
FROM [RECIPE_IMAGES] RI 
	INNER JOIN [RECIPES] R 
			ON RI.[RECIPE_ID] = R.[ID] 
WHERE RI.[IsDeleted] = 0 
	AND R.[IsDeleted] = 0 
	AND RI.[ID] = @PRM_RECIPE_IMAGES_ID 
	AND R.[ID] = @PRM_RECIPES_ID 
ORDER BY RI.[ID] 