SELECT R.[ID], R.[RECIPE_NAME], R.[DESCRIPTION], R.[INSTRUCTIONS], R.[CREATED_DATE], R.[IS_ACTIVE] 
FROM [RECIPE_NOTES] RN 
	INNER JOIN [RECIPES] R 
			ON RN.[RECIPE_ID] = R.[ID] 
WHERE RN.[IsDeleted] = 0 
	AND R.[IsDeleted] = 0 
	AND R.[ID] = @PRM_RECIPES_ID 
ORDER BY R.[ID] 