SELECT RI.[ID], RI.[RECIPE_ID], RI.[INGREDIENT_NAME], RI.[QUANTITY], RI.[UNIT] 
FROM [RECIPE_INGREDIENTS] RI 
	INNER JOIN [RECIPES] R 
			ON RI.[RECIPE_ID] = R.[ID] 
WHERE RI.[IsDeleted] = 0 
	AND R.[IsDeleted] = 0 
	AND RI.[ID] = @PRM_RECIPE_INGREDIENTS_ID 
	AND R.[ID] = @PRM_RECIPES_ID 
ORDER BY RI.[ID] 