SELECT R.[ID], R.[RECIPE_NAME], R.[DESCRIPTION], R.[INSTRUCTIONS], R.[CREATED_DATE], R.[IS_ACTIVE] 
FROM [RECIPE_EQUIPMENTS] RE 
	INNER JOIN [RECIPES] R 
			ON RE.[RECIPE_ID] = R.[ID] 
WHERE RE.[IsDeleted] = 0 
	AND R.[IsDeleted] = 0 
	AND R.[ID] = @PRM_RECIPES_ID 
ORDER BY R.[ID] 