SELECT [ID], [RECIPE_NAME], [DESCRIPTION] 
FROM [RECIPES] 
WHERE [IsDeleted] = 0 
	AND [RECIPE_NAME] LIKE '%' + @PRM_RECIPES_RECIPE_NAME + '%' 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 