//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo-kahve.Common.Models; using  QuickCode . Demo
-kahve.IdentityModule.Domain.Entities; using  QuickCode . Demo
-kahve.IdentityModule.Application.Interfaces.Repositories; using  System . Threading . Tasks ;  using  Dapper ;  using  Microsoft . EntityFrameworkCore ;  using  Microsoft . Extensions . Logging ;  using  QuickCode . Demo
-kahve.Common; using  QuickCode . Demo
-kahve.Common.Extensions; using  QuickCode . Demo
-kahve.Common.Helpers; using  QuickCode . Demo
-kahve.IdentityModule.Persistence.Contexts; using  QuickCode . Demo
-kahve.IdentityModule.Application.Dtos.TopicWorkflow; using  QuickCode . Demo
-kahve.IdentityModule.Application.Mappings; using  QuickCode . Demo
-kahve.IdentityModule.Persistence.Sql; using  QuickCode . Demo
-kahve.IdentityModule.Domain.Enums;
namespace QuickCode.Demo - kahve . IdentityModule . Persistence . Repositories {
    public partial class TopicWorkflowRepository : BaseRepository, ITopicWorkflowRepository
    {
        public async Task<RepoResponse<List<GetWorkflowsResponseDto>>> GetWorkflowsAsync(string topicWorkflowsKafkaEventsTopicName)
        {
            return await ExecuteWithExceptionHandling("GetWorkflows", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.TopicWorkflow.Query.GetWorkflows);
                var parameters = new
                {
                    PRM_TopicWorkflows_KafkaEventsTopicName = topicWorkflowsKafkaEventsTopicName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetWorkflowsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in TopicWorkflow");
            });
        }

        public async Task<RepoResponse<List<GetWorkflows2ResponseDto>>> GetWorkflows2Async(string topicWorkflowsKafkaEventsTopicName)
        {
            return await ExecuteWithExceptionHandling("GetWorkflows2", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.TopicWorkflow.Query.GetWorkflows2);
                var parameters = new
                {
                    PRM_TopicWorkflows_KafkaEventsTopicName = topicWorkflowsKafkaEventsTopicName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetWorkflows2ResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in TopicWorkflow");
            });
        }

        public async Task<RepoResponse<List<GetTopicWorkflowsResponseDto>>> GetTopicWorkflowsAsync(string kafkaEventsTopicName, HttpMethodType apiMethodDefinitionsHttpMethod)
        {
            return await ExecuteWithExceptionHandling("GetTopicWorkflows", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.TopicWorkflow.Query.GetTopicWorkflows);
                var parameters = new
                {
                    PRM_KafkaEvents_TopicName = kafkaEventsTopicName,
                    PRM_ApiMethodDefinitions_HttpMethod = apiMethodDefinitionsHttpMethod
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetTopicWorkflowsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in TopicWorkflow");
            });
        }
    }
}