//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo-kahve.Common.Models; using  QuickCode . Demo
-kahve.IdentityModule.Domain.Entities; using  QuickCode . Demo
-kahve.IdentityModule.Application.Interfaces.Repositories; using  System . Threading . Tasks ;  using  Dapper ;  using  Microsoft . EntityFrameworkCore ;  using  Microsoft . Extensions . Logging ;  using  QuickCode . Demo
-kahve.Common; using  QuickCode . Demo
-kahve.Common.Extensions; using  QuickCode . Demo
-kahve.Common.Helpers; using  QuickCode . Demo
-kahve.IdentityModule.Persistence.Contexts; using  QuickCode . Demo
-kahve.IdentityModule.Application.Dtos.RefreshToken; using  QuickCode . Demo
-kahve.IdentityModule.Application.Mappings; using  QuickCode . Demo
-kahve.IdentityModule.Persistence.Sql; using  QuickCode . Demo
-kahve.IdentityModule.Domain.Enums;
namespace QuickCode.Demo - kahve . IdentityModule . Persistence . Repositories {
    public partial class RefreshTokenRepository : BaseRepository, IRefreshTokenRepository
    {
        public async Task<RepoResponse<GetRefreshTokenResponseDto>> GetRefreshTokenAsync(string refreshTokensToken)
        {
            return await ExecuteWithExceptionHandling("GetRefreshToken", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.RefreshToken.Query.GetRefreshToken);
                var parameters = new
                {
                    PRM_RefreshTokens_Token = refreshTokensToken
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetRefreshTokenResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in RefreshToken");
            });
        }
    }
}