//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo-kahve.Common.Models; using  QuickCode . Demo
-kahve.ProductionModuleModule.Domain.Entities; using  QuickCode . Demo
-kahve.ProductionModuleModule.Application.Interfaces.Repositories; using  System . Threading . Tasks ;  using  Dapper ;  using  Microsoft . EntityFrameworkCore ;  using  Microsoft . Extensions . Logging ;  using  QuickCode . Demo
-kahve.Common; using  QuickCode . Demo
-kahve.Common.Extensions; using  QuickCode . Demo
-kahve.Common.Helpers; using  QuickCode . Demo
-kahve.ProductionModuleModule.Persistence.Contexts; using  QuickCode . Demo
-kahve.ProductionModuleModule.Application.Dtos.RoastingProcess; using  QuickCode . Demo
-kahve.ProductionModuleModule.Application.Mappings; using  QuickCode . Demo
-kahve.ProductionModuleModule.Persistence.Sql; using  QuickCode . Demo
-kahve.ProductionModuleModule.Domain.Enums;
namespace QuickCode.Demo - kahve . ProductionModuleModule . Persistence . Repositories {
    public partial class RoastingProcessRepository : BaseRepository, IRoastingProcessRepository
    {
        public async Task<RepoResponse<List<GetByBeanBatchIdResponseDto>>> GetByBeanBatchIdAsync(int roastingProcessesBeanBatchId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetByBeanBatchId", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByBeanBatchIdResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.RoastingProcess.Query.GetByBeanBatchId);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_ROASTING_PROCESSES_BEAN_BATCH_ID = roastingProcessesBeanBatchId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetByBeanBatchIdResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in RoastingProcess");
                }
            });
        }

        public async Task<RepoResponse<List<GetByStatusResponseDto>>> GetByStatusAsync(ProcessStatus roastingProcessesProcessStatus, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetByStatus", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByStatusResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.RoastingProcess.Query.GetByStatus);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_ROASTING_PROCESSES_PROCESS_STATUS = roastingProcessesProcessStatus,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetByStatusResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in RoastingProcess");
                }
            });
        }

        public async Task<RepoResponse<List<GetGrindingProcessesForRoastingProcessesResponseDto>>> GetGrindingProcessesForRoastingProcessesAsync(int roastingProcessesId)
        {
            return await ExecuteWithExceptionHandling("GetGrindingProcessesForRoastingProcesses", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.RoastingProcess.Query.GetGrindingProcessesForRoastingProcesses);
                var parameters = new
                {
                    PRM_ROASTING_PROCESSES_ID = roastingProcessesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetGrindingProcessesForRoastingProcessesResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in RoastingProcess");
            });
        }

        public async Task<RepoResponse<GetGrindingProcessesForRoastingProcessesResponseDto>> GetGrindingProcessesForRoastingProcessesDetailsAsync(int roastingProcessesId, int grindingProcessesId)
        {
            return await ExecuteWithExceptionHandling("GetGrindingProcessesForRoastingProcessesDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.RoastingProcess.Query.GetGrindingProcessesForRoastingProcessesDetails);
                var parameters = new
                {
                    PRM_GRINDING_PROCESSES_ID = grindingProcessesId,
                    PRM_ROASTING_PROCESSES_ID = roastingProcessesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetGrindingProcessesForRoastingProcessesResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in RoastingProcess");
            });
        }
    }
}