//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo-kahve.ProductionModuleModule.Application.Dtos.CoffeeBean; using  QuickCode . Demo
-kahve.ProductionModuleModule.Domain.Entities; using  QuickCode . Demo
-kahve.ProductionModuleModule.Domain.Enums;
namespace QuickCode.Demo - kahve . ProductionModuleModule . Application . Mappings {
    public static class CoffeeBeanMappings
    {
        public static List<CoffeeBeanDto> ToDto(this IEnumerable<CoffeeBean> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static CoffeeBeanDto ToDto(this CoffeeBean model)
        {
            return new CoffeeBeanDto
            {
                Id = model.Id,
                BatchId = model.BatchId,
                Origin = model.Origin,
                WeightKg = model.WeightKg,
                ArrivalDate = model.ArrivalDate,
                IsActive = model.IsActive,
                CreatedDate = model.CreatedDate
            };
        }

        public static CoffeeBean ToEntity(this CoffeeBeanDto model)
        {
            return new CoffeeBean
            {
                Id = model.Id,
                BatchId = model.BatchId,
                Origin = model.Origin,
                WeightKg = model.WeightKg,
                ArrivalDate = model.ArrivalDate,
                IsActive = model.IsActive,
                CreatedDate = model.CreatedDate
            };
        }
    }
}