//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo-kahve.ProductionModuleModule.Application.Dtos.GrindingProcess; using  QuickCode . Demo
-kahve.ProductionModuleModule.Domain.Entities; using  QuickCode . Demo
-kahve.ProductionModuleModule.Domain.Enums;
namespace QuickCode.Demo - kahve . ProductionModuleModule . Application . Mappings {
    public static class GrindingProcessMappings
    {
        public static List<GrindingProcessDto> ToDto(this IEnumerable<GrindingProcess> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static GrindingProcessDto ToDto(this GrindingProcess model)
        {
            return new GrindingProcessDto
            {
                Id = model.Id,
                RoastingProcessId = model.RoastingProcessId,
                GrindingDate = model.GrindingDate,
                GrindSize = model.GrindSize,
                ProcessStatus = model.ProcessStatus,
                CreatedDate = model.CreatedDate
            };
        }

        public static GrindingProcess ToEntity(this GrindingProcessDto model)
        {
            return new GrindingProcess
            {
                Id = model.Id,
                RoastingProcessId = model.RoastingProcessId,
                GrindingDate = model.GrindingDate,
                GrindSize = model.GrindSize,
                ProcessStatus = model.ProcessStatus,
                CreatedDate = model.CreatedDate
            };
        }
    }
}