//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo-kahve.ProductionModuleModule.Application.Dtos.PackagingProcess; using  QuickCode . Demo
-kahve.ProductionModuleModule.Domain.Entities; using  QuickCode . Demo
-kahve.ProductionModuleModule.Domain.Enums;
namespace QuickCode.Demo - kahve . ProductionModuleModule . Application . Mappings {
    public static class PackagingProcessMappings
    {
        public static List<PackagingProcessDto> ToDto(this IEnumerable<PackagingProcess> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static PackagingProcessDto ToDto(this PackagingProcess model)
        {
            return new PackagingProcessDto
            {
                Id = model.Id,
                GrindingProcessId = model.GrindingProcessId,
                PackagingDate = model.PackagingDate,
                PackageSizeGrams = model.PackageSizeGrams,
                ProcessStatus = model.ProcessStatus,
                CreatedDate = model.CreatedDate
            };
        }

        public static PackagingProcess ToEntity(this PackagingProcessDto model)
        {
            return new PackagingProcess
            {
                Id = model.Id,
                GrindingProcessId = model.GrindingProcessId,
                PackagingDate = model.PackagingDate,
                PackageSizeGrams = model.PackageSizeGrams,
                ProcessStatus = model.ProcessStatus,
                CreatedDate = model.CreatedDate
            };
        }
    }
}