//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo-kahve.ProductionModuleModule.Application.Dtos.ProcessEquipment; using  QuickCode . Demo
-kahve.ProductionModuleModule.Domain.Entities; using  QuickCode . Demo
-kahve.ProductionModuleModule.Domain.Enums;
namespace QuickCode.Demo - kahve . ProductionModuleModule . Application . Mappings {
    public static class ProcessEquipmentMappings
    {
        public static List<ProcessEquipmentDto> ToDto(this IEnumerable<ProcessEquipment> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static ProcessEquipmentDto ToDto(this ProcessEquipment model)
        {
            return new ProcessEquipmentDto
            {
                Id = model.Id,
                EquipmentName = model.EquipmentName,
                EquipmentType = model.EquipmentType,
                LastMaintenanceDate = model.LastMaintenanceDate,
                IsActive = model.IsActive,
                CreatedDate = model.CreatedDate
            };
        }

        public static ProcessEquipment ToEntity(this ProcessEquipmentDto model)
        {
            return new ProcessEquipment
            {
                Id = model.Id,
                EquipmentName = model.EquipmentName,
                EquipmentType = model.EquipmentType,
                LastMaintenanceDate = model.LastMaintenanceDate,
                IsActive = model.IsActive,
                CreatedDate = model.CreatedDate
            };
        }
    }
}