//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo-kahve.ProductionModuleModule.Application.Dtos.ProductionError; using  QuickCode . Demo
-kahve.ProductionModuleModule.Domain.Entities; using  QuickCode . Demo
-kahve.ProductionModuleModule.Domain.Enums;
namespace QuickCode.Demo - kahve . ProductionModuleModule . Application . Mappings {
    public static class ProductionErrorMappings
    {
        public static List<ProductionErrorDto> ToDto(this IEnumerable<ProductionError> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static ProductionErrorDto ToDto(this ProductionError model)
        {
            return new ProductionErrorDto
            {
                Id = model.Id,
                ProcessId = model.ProcessId,
                ErrorDate = model.ErrorDate,
                ErrorDescription = model.ErrorDescription,
                ErrorSeverity = model.ErrorSeverity,
                CreatedDate = model.CreatedDate
            };
        }

        public static ProductionError ToEntity(this ProductionErrorDto model)
        {
            return new ProductionError
            {
                Id = model.Id,
                ProcessId = model.ProcessId,
                ErrorDate = model.ErrorDate,
                ErrorDescription = model.ErrorDescription,
                ErrorSeverity = model.ErrorSeverity,
                CreatedDate = model.CreatedDate
            };
        }
    }
}