//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo-kahve.ProductionModuleModule.Application.Dtos.RoastingProcess; using  QuickCode . Demo
-kahve.ProductionModuleModule.Domain.Entities; using  QuickCode . Demo
-kahve.ProductionModuleModule.Domain.Enums;
namespace QuickCode.Demo - kahve . ProductionModuleModule . Application . Mappings {
    public static class RoastingProcessMappings
    {
        public static List<RoastingProcessDto> ToDto(this IEnumerable<RoastingProcess> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static RoastingProcessDto ToDto(this RoastingProcess model)
        {
            return new RoastingProcessDto
            {
                Id = model.Id,
                BeanBatchId = model.BeanBatchId,
                RoastingDate = model.RoastingDate,
                TemperatureCelsius = model.TemperatureCelsius,
                DurationMinutes = model.DurationMinutes,
                ProcessStatus = model.ProcessStatus,
                CreatedDate = model.CreatedDate
            };
        }

        public static RoastingProcess ToEntity(this RoastingProcessDto model)
        {
            return new RoastingProcess
            {
                Id = model.Id,
                BeanBatchId = model.BeanBatchId,
                RoastingDate = model.RoastingDate,
                TemperatureCelsius = model.TemperatureCelsius,
                DurationMinutes = model.DurationMinutes,
                ProcessStatus = model.ProcessStatus,
                CreatedDate = model.CreatedDate
            };
        }
    }
}