SELECT [ID], [BEAN_BATCH_ID], [ROASTING_DATE], [TEMPERATURE_CELSIUS], [DURATION_MINUTES], [PROCESS_STATUS] 
FROM [ROASTING_PROCESSES] 
WHERE [IsDeleted] = 0 
	AND [PROCESS_STATUS] = @PRM_ROASTING_PROCESSES_PROCESS_STATUS 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 