SELECT GP.[ID], GP.[ROASTING_PROCESS_ID], GP.[GRINDING_DATE], GP.[GRIND_SIZE], GP.[PROCESS_STATUS], GP.[CREATED_DATE] 
FROM [GRINDING_PROCESSES] GP 
	INNER JOIN [ROASTING_PROCESSES] RP 
			ON GP.[ROASTING_PROCESS_ID] = RP.[ID] 
WHERE GP.[IsDeleted] = 0 
	AND RP.[IsDeleted] = 0 
	AND GP.[ID] = @PRM_GRINDING_PROCESSES_ID 
	AND RP.[ID] = @PRM_ROASTING_PROCESSES_ID 
ORDER BY GP.[ID] 