SELECT RP.[ID], RP.[BEAN_BATCH_ID], RP.[ROASTING_DATE], RP.[TEMPERATURE_CELSIUS], RP.[DURATION_MINUTES], RP.[PROCESS_STATUS], RP.[CREATED_DATE] 
FROM [GRINDING_PROCESSES] GP 
	INNER JOIN [ROASTING_PROCESSES] RP 
			ON GP.[ROASTING_PROCESS_ID] = RP.[ID] 
WHERE GP.[IsDeleted] = 0 
	AND RP.[IsDeleted] = 0 
	AND RP.[ID] = @PRM_ROASTING_PROCESSES_ID 
ORDER BY RP.[ID] 