SELECT [ID], [RECIPE_ID] 
FROM [RECIPE_CATEGORY_ASSIGNMENTS] 
WHERE [IsDeleted] = 0 
	AND [CATEGORY_ID] = @PRM_RECIPE_CATEGORY_ASSIGNMENTS_CATEGORY_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 