SELECT [ID], [CATEGORY_ID] 
FROM [RECIPE_CATEGORY_ASSIGNMENTS] 
WHERE [IsDeleted] = 0 
	AND [RECIPE_ID] = @PRM_RECIPE_CATEGORY_ASSIGNMENTS_RECIPE_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 