//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo-kahve.Common.Models; using  QuickCode . Demo
-kahve.IdentityModule.Domain.Entities; using  QuickCode . Demo
-kahve.IdentityModule.Application.Dtos.ApiMethodAccessGrant; using  System . Threading . Tasks ;  using  QuickCode . Demo
-kahve.IdentityModule.Domain.Enums;
namespace QuickCode.Demo - kahve . IdentityModule . Application . Interfaces . Repositories {
    public partial interface IApiMethodAccessGrantRepository : IBaseRepository<ApiMethodAccessGrantDto>
    {
        Task<RepoResponse<ApiMethodAccessGrantDto>> GetByPkAsync(string permissionGroupName, string apiMethodDefinitionKey);
        Task<RepoResponse<List<GetApiMethodAccessGrantNamesResponseDto>>> GetApiMethodAccessGrantNamesAsync(string apiMethodAccessGrantsPermissionGroupName);
        Task<RepoResponse<int>> ClearApiMethodAccessGrantsAsync();
    }
}