//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo-kahve.Common.Models; using  QuickCode . Demo
-kahve.IdentityModule.Domain.Entities; using  QuickCode . Demo
-kahve.IdentityModule.Application.Dtos.TopicWorkflow; using  System . Threading . Tasks ;  using  QuickCode . Demo
-kahve.IdentityModule.Domain.Enums;
namespace QuickCode.Demo - kahve . IdentityModule . Application . Interfaces . Repositories {
    public partial interface ITopicWorkflowRepository : IBaseRepository<TopicWorkflowDto>
    {
        Task<RepoResponse<TopicWorkflowDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetWorkflowsResponseDto>>> GetWorkflowsAsync(string topicWorkflowsKafkaEventsTopicName);
        Task<RepoResponse<List<GetWorkflows2ResponseDto>>> GetWorkflows2Async(string topicWorkflowsKafkaEventsTopicName);
        Task<RepoResponse<List<GetTopicWorkflowsResponseDto>>> GetTopicWorkflowsAsync(string kafkaEventsTopicName, HttpMethodType apiMethodDefinitionsHttpMethod);
    }
}