SELECT [ID], [IMAGE_URL], [DESCRIPTION] 
FROM [RECIPE_IMAGES] 
WHERE [IsDeleted] = 0 
	AND [RECIPE_ID] = @PRM_RECIPE_IMAGES_RECIPE_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 