//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo-kahve.RecipeModuleModule.Application.Dtos.RecipeIngredient; using  QuickCode . Demo
-kahve.RecipeModuleModule.Domain.Entities;
namespace QuickCode.Demo - kahve . RecipeModuleModule . Application . Mappings {
    public static class RecipeIngredientMappings
    {
        public static List<RecipeIngredientDto> ToDto(this IEnumerable<RecipeIngredient> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static RecipeIngredientDto ToDto(this RecipeIngredient model)
        {
            return new RecipeIngredientDto
            {
                Id = model.Id,
                RecipeId = model.RecipeId,
                IngredientName = model.IngredientName,
                Quantity = model.Quantity,
                Unit = model.Unit
            };
        }

        public static RecipeIngredient ToEntity(this RecipeIngredientDto model)
        {
            return new RecipeIngredient
            {
                Id = model.Id,
                RecipeId = model.RecipeId,
                IngredientName = model.IngredientName,
                Quantity = model.Quantity,
                Unit = model.Unit
            };
        }
    }
}