//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo-kahve.RecipeModuleModule.Application.Dtos.Recipe; using  QuickCode . Demo
-kahve.RecipeModuleModule.Domain.Entities;
namespace QuickCode.Demo - kahve . RecipeModuleModule . Application . Mappings {
    public static class RecipeMappings
    {
        public static List<RecipeDto> ToDto(this IEnumerable<Recipe> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static RecipeDto ToDto(this Recipe model)
        {
            return new RecipeDto
            {
                Id = model.Id,
                RecipeName = model.RecipeName,
                Description = model.Description,
                Instructions = model.Instructions,
                CreatedDate = model.CreatedDate,
                IsActive = model.IsActive
            };
        }

        public static Recipe ToEntity(this RecipeDto model)
        {
            return new Recipe
            {
                Id = model.Id,
                RecipeName = model.RecipeName,
                Description = model.Description,
                Instructions = model.Instructions,
                CreatedDate = model.CreatedDate,
                IsActive = model.IsActive
            };
        }
    }
}