//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo-kahve.RecipeModuleModule.Application.Dtos.RecipeCategoryAssignment; using  QuickCode . Demo
-kahve.RecipeModuleModule.Domain.Entities;
namespace QuickCode.Demo - kahve . RecipeModuleModule . Application . Mappings {
    public static class RecipeCategoryAssignmentMappings
    {
        public static List<RecipeCategoryAssignmentDto> ToDto(this IEnumerable<RecipeCategoryAssignment> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static RecipeCategoryAssignmentDto ToDto(this RecipeCategoryAssignment model)
        {
            return new RecipeCategoryAssignmentDto
            {
                Id = model.Id,
                RecipeId = model.RecipeId,
                CategoryId = model.CategoryId
            };
        }

        public static RecipeCategoryAssignment ToEntity(this RecipeCategoryAssignmentDto model)
        {
            return new RecipeCategoryAssignment
            {
                Id = model.Id,
                RecipeId = model.RecipeId,
                CategoryId = model.CategoryId
            };
        }
    }
}