//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo-kahve.RecipeModuleModule.Application.Dtos.RecipeNote; using  QuickCode . Demo
-kahve.RecipeModuleModule.Domain.Entities;
namespace QuickCode.Demo - kahve . RecipeModuleModule . Application . Mappings {
    public static class RecipeNoteMappings
    {
        public static List<RecipeNoteDto> ToDto(this IEnumerable<RecipeNote> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static RecipeNoteDto ToDto(this RecipeNote model)
        {
            return new RecipeNoteDto
            {
                Id = model.Id,
                RecipeId = model.RecipeId,
                NoteText = model.NoteText,
                CreatedDate = model.CreatedDate
            };
        }

        public static RecipeNote ToEntity(this RecipeNoteDto model)
        {
            return new RecipeNote
            {
                Id = model.Id,
                RecipeId = model.RecipeId,
                NoteText = model.NoteText,
                CreatedDate = model.CreatedDate
            };
        }
    }
}