//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo-kahve.RecipeModuleModule.Application.Dtos.RecipeEquipment; using  QuickCode . Demo
-kahve.RecipeModuleModule.Domain.Entities;
namespace QuickCode.Demo - kahve . RecipeModuleModule . Application . Mappings {
    public static class RecipeEquipmentMappings
    {
        public static List<RecipeEquipmentDto> ToDto(this IEnumerable<RecipeEquipment> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static RecipeEquipmentDto ToDto(this RecipeEquipment model)
        {
            return new RecipeEquipmentDto
            {
                Id = model.Id,
                RecipeId = model.RecipeId,
                EquipmentName = model.EquipmentName,
                EquipmentDescription = model.EquipmentDescription
            };
        }

        public static RecipeEquipment ToEntity(this RecipeEquipmentDto model)
        {
            return new RecipeEquipment
            {
                Id = model.Id,
                RecipeId = model.RecipeId,
                EquipmentName = model.EquipmentName,
                EquipmentDescription = model.EquipmentDescription
            };
        }
    }
}