//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo-kahve.RecipeModuleModule.Application.Dtos.RecipeImage; using  QuickCode . Demo
-kahve.RecipeModuleModule.Domain.Entities;
namespace QuickCode.Demo - kahve . RecipeModuleModule . Application . Mappings {
    public static class RecipeImageMappings
    {
        public static List<RecipeImageDto> ToDto(this IEnumerable<RecipeImage> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static RecipeImageDto ToDto(this RecipeImage model)
        {
            return new RecipeImageDto
            {
                Id = model.Id,
                RecipeId = model.RecipeId,
                ImageUrl = model.ImageUrl,
                Description = model.Description
            };
        }

        public static RecipeImage ToEntity(this RecipeImageDto model)
        {
            return new RecipeImage
            {
                Id = model.Id,
                RecipeId = model.RecipeId,
                ImageUrl = model.ImageUrl,
                Description = model.Description
            };
        }
    }
}