//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo-kahve.RecipeModuleModule.Application.Dtos.RecipeCategory; using  QuickCode . Demo
-kahve.RecipeModuleModule.Domain.Entities;
namespace QuickCode.Demo - kahve . RecipeModuleModule . Application . Mappings {
    public static class RecipeCategoryMappings
    {
        public static List<RecipeCategoryDto> ToDto(this IEnumerable<RecipeCategory> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static RecipeCategoryDto ToDto(this RecipeCategory model)
        {
            return new RecipeCategoryDto
            {
                Id = model.Id,
                CategoryName = model.CategoryName,
                Description = model.Description,
                IsActive = model.IsActive
            };
        }

        public static RecipeCategory ToEntity(this RecipeCategoryDto model)
        {
            return new RecipeCategory
            {
                Id = model.Id,
                CategoryName = model.CategoryName,
                Description = model.Description,
                IsActive = model.IsActive
            };
        }
    }
}