//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo-kahve.Common.Models; using  QuickCode . Demo
-kahve.ProductionModuleModule.Domain.Entities; using  QuickCode . Demo
-kahve.ProductionModuleModule.Application.Interfaces.Repositories; using  System . Threading . Tasks ;  using  Dapper ;  using  Microsoft . EntityFrameworkCore ;  using  Microsoft . Extensions . Logging ;  using  QuickCode . Demo
-kahve.Common; using  QuickCode . Demo
-kahve.Common.Extensions; using  QuickCode . Demo
-kahve.Common.Helpers; using  QuickCode . Demo
-kahve.ProductionModuleModule.Persistence.Contexts; using  QuickCode . Demo
-kahve.ProductionModuleModule.Application.Dtos.GrindingProcess; using  QuickCode . Demo
-kahve.ProductionModuleModule.Application.Mappings; using  QuickCode . Demo
-kahve.ProductionModuleModule.Persistence.Sql; using  QuickCode . Demo
-kahve.ProductionModuleModule.Domain.Enums;
namespace QuickCode.Demo - kahve . ProductionModuleModule . Persistence . Repositories {
    public partial class GrindingProcessRepository : BaseRepository, IGrindingProcessRepository
    {
        public async Task<RepoResponse<List<GetByRoastingProcessIdResponseDto>>> GetByRoastingProcessIdAsync(int grindingProcessesRoastingProcessId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetByRoastingProcessId", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByRoastingProcessIdResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.GrindingProcess.Query.GetByRoastingProcessId);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_GRINDING_PROCESSES_ROASTING_PROCESS_ID = grindingProcessesRoastingProcessId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetByRoastingProcessIdResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in GrindingProcess");
                }
            });
        }

        public async Task<RepoResponse<List<GetByStatusResponseDto>>> GetByStatusAsync(ProcessStatus grindingProcessesProcessStatus, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetByStatus", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByStatusResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.GrindingProcess.Query.GetByStatus);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_GRINDING_PROCESSES_PROCESS_STATUS = grindingProcessesProcessStatus,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetByStatusResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in GrindingProcess");
                }
            });
        }

        public async Task<RepoResponse<List<GetPackagingProcessesForGrindingProcessesResponseDto>>> GetPackagingProcessesForGrindingProcessesAsync(int grindingProcessesId)
        {
            return await ExecuteWithExceptionHandling("GetPackagingProcessesForGrindingProcesses", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.GrindingProcess.Query.GetPackagingProcessesForGrindingProcesses);
                var parameters = new
                {
                    PRM_GRINDING_PROCESSES_ID = grindingProcessesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetPackagingProcessesForGrindingProcessesResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in GrindingProcess");
            });
        }

        public async Task<RepoResponse<GetPackagingProcessesForGrindingProcessesResponseDto>> GetPackagingProcessesForGrindingProcessesDetailsAsync(int grindingProcessesId, int packagingProcessesId)
        {
            return await ExecuteWithExceptionHandling("GetPackagingProcessesForGrindingProcessesDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.GrindingProcess.Query.GetPackagingProcessesForGrindingProcessesDetails);
                var parameters = new
                {
                    PRM_PACKAGING_PROCESSES_ID = packagingProcessesId,
                    PRM_GRINDING_PROCESSES_ID = grindingProcessesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetPackagingProcessesForGrindingProcessesResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in GrindingProcess");
            });
        }
    }
}