//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo-kahve.Common.Models; using  QuickCode . Demo
-kahve.ProductionModuleModule.Domain.Entities; using  QuickCode . Demo
-kahve.ProductionModuleModule.Application.Interfaces.Repositories; using  System . Threading . Tasks ;  using  Dapper ;  using  Microsoft . EntityFrameworkCore ;  using  Microsoft . Extensions . Logging ;  using  QuickCode . Demo
-kahve.Common; using  QuickCode . Demo
-kahve.Common.Extensions; using  QuickCode . Demo
-kahve.Common.Helpers; using  QuickCode . Demo
-kahve.ProductionModuleModule.Persistence.Contexts; using  QuickCode . Demo
-kahve.ProductionModuleModule.Application.Dtos.GrindingProcess; using  QuickCode . Demo
-kahve.ProductionModuleModule.Application.Mappings; using  QuickCode . Demo
-kahve.ProductionModuleModule.Persistence.Sql; using  QuickCode . Demo
-kahve.ProductionModuleModule.Domain.Enums;
namespace QuickCode.Demo - kahve . ProductionModuleModule . Persistence . Repositories {
    public partial class GrindingProcessRepository : BaseRepository, IGrindingProcessRepository
    {
        public async Task<RepoResponse<int>> UpdateStatusAsync(int grindingProcessesId, UpdateStatusRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling("GrindingProcess", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.GrindingProcess.Command.UpdateStatus);
                var parameters = new
                {
                    GRINDING_PROCESSES_PROCESS_STATUS = updateRequest.GrindingProcessesProcessStatus,
                    PRM_GRINDING_PROCESSES_ID = grindingProcessesId
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }
    }
}