SELECT [ID], [GRINDING_PROCESS_ID], [PACKAGING_DATE], [PACKAGE_SIZE_GRAMS], [PROCESS_STATUS] 
FROM [PACKAGING_PROCESSES] 
WHERE [IsDeleted] = 0 
	AND [PROCESS_STATUS] = @PRM_PACKAGING_PROCESSES_PROCESS_STATUS 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 