//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo-kahve.Common.Models; using  QuickCode . Demo
-kahve.IdentityModule.Domain.Entities; using  QuickCode . Demo
-kahve.IdentityModule.Application.Interfaces.Repositories; using  System . Threading . Tasks ;  using  Dapper ;  using  Microsoft . EntityFrameworkCore ;  using  Microsoft . Extensions . Logging ;  using  QuickCode . Demo
-kahve.Common; using  QuickCode . Demo
-kahve.Common.Extensions; using  QuickCode . Demo
-kahve.Common.Helpers; using  QuickCode . Demo
-kahve.IdentityModule.Persistence.Contexts; using  QuickCode . Demo
-kahve.IdentityModule.Application.Dtos.Module; using  QuickCode . Demo
-kahve.IdentityModule.Application.Mappings; using  QuickCode . Demo
-kahve.IdentityModule.Persistence.Sql; using  QuickCode . Demo
-kahve.IdentityModule.Domain.Enums;
namespace QuickCode.Demo - kahve . IdentityModule . Persistence . Repositories {
    public partial class ModuleRepository : BaseRepository, IModuleRepository
    {
        public async Task<RepoResponse<bool>> ModuleNameIsExistsAsync(string modulesName)
        {
            return await ExecuteWithExceptionHandling("ModuleNameIsExists", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Module.Query.ModuleNameIsExists);
                var parameters = new
                {
                    PRM_Modules_Name = modulesName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var exists = await connection.ExecuteScalarAsync<bool>(sql, parameters);
                return BuildBoolResponse(exists, $"Not found in Module");
            });
        }

        public async Task<RepoResponse<List<GetModelsForModulesResponseDto>>> GetModelsForModulesAsync(string modulesName)
        {
            return await ExecuteWithExceptionHandling("GetModelsForModules", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Module.Query.GetModelsForModules);
                var parameters = new
                {
                    PRM_Modules_Name = modulesName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetModelsForModulesResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in Module");
            });
        }

        public async Task<RepoResponse<GetModelsForModulesResponseDto>> GetModelsForModulesDetailsAsync(string modulesName, string modelsName)
        {
            return await ExecuteWithExceptionHandling("GetModelsForModulesDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Module.Query.GetModelsForModulesDetails);
                var parameters = new
                {
                    PRM_Models_Name = modelsName,
                    PRM_Modules_Name = modulesName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetModelsForModulesResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Module");
            });
        }

        public async Task<RepoResponse<List<GetApiMethodDefinitionsForModulesResponseDto>>> GetApiMethodDefinitionsForModulesAsync(string modulesName)
        {
            return await ExecuteWithExceptionHandling("GetApiMethodDefinitionsForModules", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Module.Query.GetApiMethodDefinitionsForModules);
                var parameters = new
                {
                    PRM_Modules_Name = modulesName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetApiMethodDefinitionsForModulesResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in Module");
            });
        }

        public async Task<RepoResponse<GetApiMethodDefinitionsForModulesResponseDto>> GetApiMethodDefinitionsForModulesDetailsAsync(string modulesName, string apiMethodDefinitionsKey)
        {
            return await ExecuteWithExceptionHandling("GetApiMethodDefinitionsForModulesDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Module.Query.GetApiMethodDefinitionsForModulesDetails);
                var parameters = new
                {
                    PRM_ApiMethodDefinitions_Key = apiMethodDefinitionsKey,
                    PRM_Modules_Name = modulesName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetApiMethodDefinitionsForModulesResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Module");
            });
        }

        public async Task<RepoResponse<List<GetPortalPageDefinitionsForModulesResponseDto>>> GetPortalPageDefinitionsForModulesAsync(string modulesName)
        {
            return await ExecuteWithExceptionHandling("GetPortalPageDefinitionsForModules", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Module.Query.GetPortalPageDefinitionsForModules);
                var parameters = new
                {
                    PRM_Modules_Name = modulesName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetPortalPageDefinitionsForModulesResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in Module");
            });
        }

        public async Task<RepoResponse<GetPortalPageDefinitionsForModulesResponseDto>> GetPortalPageDefinitionsForModulesDetailsAsync(string modulesName, string portalPageDefinitionsKey)
        {
            return await ExecuteWithExceptionHandling("GetPortalPageDefinitionsForModulesDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Module.Query.GetPortalPageDefinitionsForModulesDetails);
                var parameters = new
                {
                    PRM_PortalPageDefinitions_Key = portalPageDefinitionsKey,
                    PRM_Modules_Name = modulesName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetPortalPageDefinitionsForModulesResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Module");
            });
        }
    }
}