//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo-kahve.Common.Models; using  QuickCode . Demo
-kahve.RecipeModuleModule.Domain.Entities; using  QuickCode . Demo
-kahve.RecipeModuleModule.Application.Dtos.RecipeCategory; using  System . Threading . Tasks ; 
namespace QuickCode.Demo - kahve . RecipeModuleModule . Application . Interfaces . Repositories {
    public partial interface IRecipeCategoryRepository : IBaseRepository<RecipeCategoryDto>
    {
        Task<RepoResponse<RecipeCategoryDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetActiveResponseDto>>> GetActiveAsync(bool recipeCategoriesIsActive, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetRecipeCategoryAssignmentsForRecipeCategoriesResponseDto>>> GetRecipeCategoryAssignmentsForRecipeCategoriesAsync(int recipeCategoriesId);
        Task<RepoResponse<GetRecipeCategoryAssignmentsForRecipeCategoriesResponseDto>> GetRecipeCategoryAssignmentsForRecipeCategoriesDetailsAsync(int recipeCategoriesId, int recipeCategoryAssignmentsId);
        Task<RepoResponse<int>> DeactivateAsync(int recipeCategoriesId, DeactivateRequestDto updateRequest);
    }
}