//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo-kahve.Common.Models; using  QuickCode . Demo
-kahve.RecipeModuleModule.Domain.Entities; using  QuickCode . Demo
-kahve.RecipeModuleModule.Application.Dtos.RecipeCategoryAssignment; using  System . Threading . Tasks ; 
namespace QuickCode.Demo - kahve . RecipeModuleModule . Application . Interfaces . Repositories {
    public partial interface IRecipeCategoryAssignmentRepository : IBaseRepository<RecipeCategoryAssignmentDto>
    {
        Task<RepoResponse<RecipeCategoryAssignmentDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetByRecipeIdResponseDto>>> GetByRecipeIdAsync(int recipeCategoryAssignmentsRecipeId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetByCategoryIdResponseDto>>> GetByCategoryIdAsync(int recipeCategoryAssignmentsCategoryId, int? pageNumber = null, int? pageSize = null);
    }
}