//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo-kahve.Common.Models; using  QuickCode . Demo
-kahve.RecipeModuleModule.Domain.Entities; using  QuickCode . Demo
-kahve.RecipeModuleModule.Application.Dtos.RecipeIngredient; using  System . Threading . Tasks ; 
namespace QuickCode.Demo - kahve . RecipeModuleModule . Application . Interfaces . Repositories {
    public partial interface IRecipeIngredientRepository : IBaseRepository<RecipeIngredientDto>
    {
        Task<RepoResponse<RecipeIngredientDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetByRecipeIdResponseDto>>> GetByRecipeIdAsync(int recipeIngredientsRecipeId, int? pageNumber = null, int? pageSize = null);
    }
}