//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo-kahve.Common.Models; using  QuickCode . Demo
-kahve.RecipeModuleModule.Domain.Entities; using  QuickCode . Demo
-kahve.RecipeModuleModule.Application.Dtos.Recipe; using  System . Threading . Tasks ; 
namespace QuickCode.Demo - kahve . RecipeModuleModule . Application . Interfaces . Repositories {
    public partial interface IRecipeRepository : IBaseRepository<RecipeDto>
    {
        Task<RepoResponse<RecipeDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetActiveResponseDto>>> GetActiveAsync(bool recipesIsActive, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<SearchByNameResponseDto>>> SearchByNameAsync(string recipesRecipeName, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetRecipeIngredientsForRecipesResponseDto>>> GetRecipeIngredientsForRecipesAsync(int recipesId);
        Task<RepoResponse<GetRecipeIngredientsForRecipesResponseDto>> GetRecipeIngredientsForRecipesDetailsAsync(int recipesId, int recipeIngredientsId);
        Task<RepoResponse<List<GetRecipeEquipmentsForRecipesResponseDto>>> GetRecipeEquipmentsForRecipesAsync(int recipesId);
        Task<RepoResponse<GetRecipeEquipmentsForRecipesResponseDto>> GetRecipeEquipmentsForRecipesDetailsAsync(int recipesId, int recipeEquipmentsId);
        Task<RepoResponse<List<GetRecipeNotesForRecipesResponseDto>>> GetRecipeNotesForRecipesAsync(int recipesId);
        Task<RepoResponse<GetRecipeNotesForRecipesResponseDto>> GetRecipeNotesForRecipesDetailsAsync(int recipesId, int recipeNotesId);
        Task<RepoResponse<List<GetRecipeImagesForRecipesResponseDto>>> GetRecipeImagesForRecipesAsync(int recipesId);
        Task<RepoResponse<GetRecipeImagesForRecipesResponseDto>> GetRecipeImagesForRecipesDetailsAsync(int recipesId, int recipeImagesId);
        Task<RepoResponse<List<GetRecipeCategoryAssignmentsForRecipesResponseDto>>> GetRecipeCategoryAssignmentsForRecipesAsync(int recipesId);
        Task<RepoResponse<GetRecipeCategoryAssignmentsForRecipesResponseDto>> GetRecipeCategoryAssignmentsForRecipesDetailsAsync(int recipesId, int recipeCategoryAssignmentsId);
        Task<RepoResponse<int>> DeactivateAsync(int recipesId, DeactivateRequestDto updateRequest);
    }
}