//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo-kahve.Common.Models; using  QuickCode . Demo
-kahve.RecipeModuleModule.Domain.Entities; using  QuickCode . Demo
-kahve.RecipeModuleModule.Application.Interfaces.Repositories; using  System . Threading . Tasks ;  using  Dapper ;  using  Microsoft . EntityFrameworkCore ;  using  Microsoft . Extensions . Logging ;  using  QuickCode . Demo
-kahve.Common; using  QuickCode . Demo
-kahve.Common.Extensions; using  QuickCode . Demo
-kahve.Common.Helpers; using  QuickCode . Demo
-kahve.RecipeModuleModule.Persistence.Contexts; using  QuickCode . Demo
-kahve.RecipeModuleModule.Application.Dtos.RecipeCategory; using  QuickCode . Demo
-kahve.RecipeModuleModule.Application.Mappings; using  QuickCode . Demo
-kahve.RecipeModuleModule.Persistence.Sql;
namespace QuickCode.Demo - kahve . RecipeModuleModule . Persistence . Repositories {
    public partial class RecipeCategoryRepository : BaseRepository, IRecipeCategoryRepository
    {
        public async Task<RepoResponse<List<GetActiveResponseDto>>> GetActiveAsync(bool recipeCategoriesIsActive, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetActive", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetActiveResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.RecipeCategory.Query.GetActive);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_RECIPE_CATEGORIES_IS_ACTIVE = recipeCategoriesIsActive,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetActiveResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in RecipeCategory");
                }
            });
        }

        public async Task<RepoResponse<List<GetRecipeCategoryAssignmentsForRecipeCategoriesResponseDto>>> GetRecipeCategoryAssignmentsForRecipeCategoriesAsync(int recipeCategoriesId)
        {
            return await ExecuteWithExceptionHandling("GetRecipeCategoryAssignmentsForRecipeCategories", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.RecipeCategory.Query.GetRecipeCategoryAssignmentsForRecipeCategories);
                var parameters = new
                {
                    PRM_RECIPE_CATEGORIES_ID = recipeCategoriesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetRecipeCategoryAssignmentsForRecipeCategoriesResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in RecipeCategory");
            });
        }

        public async Task<RepoResponse<GetRecipeCategoryAssignmentsForRecipeCategoriesResponseDto>> GetRecipeCategoryAssignmentsForRecipeCategoriesDetailsAsync(int recipeCategoriesId, int recipeCategoryAssignmentsId)
        {
            return await ExecuteWithExceptionHandling("GetRecipeCategoryAssignmentsForRecipeCategoriesDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.RecipeCategory.Query.GetRecipeCategoryAssignmentsForRecipeCategoriesDetails);
                var parameters = new
                {
                    PRM_RECIPE_CATEGORY_ASSIGNMENTS_ID = recipeCategoryAssignmentsId,
                    PRM_RECIPE_CATEGORIES_ID = recipeCategoriesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetRecipeCategoryAssignmentsForRecipeCategoriesResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in RecipeCategory");
            });
        }
    }
}