//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo-kahve.Common.Models; using  QuickCode . Demo
-kahve.RecipeModuleModule.Domain.Entities; using  QuickCode . Demo
-kahve.RecipeModuleModule.Application.Interfaces.Repositories; using  System . Threading . Tasks ;  using  Dapper ;  using  Microsoft . EntityFrameworkCore ;  using  Microsoft . Extensions . Logging ;  using  QuickCode . Demo
-kahve.Common; using  QuickCode . Demo
-kahve.Common.Extensions; using  QuickCode . Demo
-kahve.Common.Helpers; using  QuickCode . Demo
-kahve.RecipeModuleModule.Persistence.Contexts; using  QuickCode . Demo
-kahve.RecipeModuleModule.Application.Dtos.RecipeImage; using  QuickCode . Demo
-kahve.RecipeModuleModule.Application.Mappings; using  QuickCode . Demo
-kahve.RecipeModuleModule.Persistence.Sql;
namespace QuickCode.Demo - kahve . RecipeModuleModule . Persistence . Repositories {
    public partial class RecipeImageRepository : BaseRepository, IRecipeImageRepository
    {
        public async Task<RepoResponse<List<GetByRecipeIdResponseDto>>> GetByRecipeIdAsync(int recipeImagesRecipeId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetByRecipeId", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByRecipeIdResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.RecipeImage.Query.GetByRecipeId);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_RECIPE_IMAGES_RECIPE_ID = recipeImagesRecipeId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetByRecipeIdResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in RecipeImage");
                }
            });
        }
    }
}