//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo-kahve.Common.Models; using  QuickCode . Demo
-kahve.IdentityModule.Domain.Entities; using  QuickCode . Demo
-kahve.IdentityModule.Application.Interfaces.Repositories; using  System . Threading . Tasks ;  using  Dapper ;  using  Microsoft . EntityFrameworkCore ;  using  Microsoft . Extensions . Logging ;  using  QuickCode . Demo
-kahve.Common; using  QuickCode . Demo
-kahve.Common.Extensions; using  QuickCode . Demo
-kahve.Common.Helpers; using  QuickCode . Demo
-kahve.IdentityModule.Persistence.Contexts; using  QuickCode . Demo
-kahve.IdentityModule.Application.Dtos.PortalPageAccessGrant; using  QuickCode . Demo
-kahve.IdentityModule.Application.Mappings; using  QuickCode . Demo
-kahve.IdentityModule.Persistence.Sql; using  QuickCode . Demo
-kahve.IdentityModule.Domain.Enums;
namespace QuickCode.Demo - kahve . IdentityModule . Persistence . Repositories {
    public partial class PortalPageAccessGrantRepository : BaseRepository, IPortalPageAccessGrantRepository
    {
        public async Task<RepoResponse<int>> ClearPortalPageAccessGrantsAsync()
        {
            return await ExecuteWithExceptionHandling("PortalPageAccessGrant", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PortalPageAccessGrant.Command.ClearPortalPageAccessGrants);
                var parameters = new
                {
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }
    }
}