//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo-kahve.Common.Models; using  QuickCode . Demo
-kahve.IdentityModule.Domain.Entities; using  QuickCode . Demo
-kahve.IdentityModule.Application.Interfaces.Repositories; using  System . Threading . Tasks ;  using  Dapper ;  using  Microsoft . EntityFrameworkCore ;  using  Microsoft . Extensions . Logging ;  using  QuickCode . Demo
-kahve.Common; using  QuickCode . Demo
-kahve.Common.Extensions; using  QuickCode . Demo
-kahve.Common.Helpers; using  QuickCode . Demo
-kahve.IdentityModule.Persistence.Contexts; using  QuickCode . Demo
-kahve.IdentityModule.Application.Dtos.PortalPageAccessGrant; using  QuickCode . Demo
-kahve.IdentityModule.Application.Mappings; using  QuickCode . Demo
-kahve.IdentityModule.Persistence.Sql; using  QuickCode . Demo
-kahve.IdentityModule.Domain.Enums;
namespace QuickCode.Demo - kahve . IdentityModule . Persistence . Repositories {
    public partial class PortalPageAccessGrantRepository : BaseRepository, IPortalPageAccessGrantRepository
    {
        public async Task<RepoResponse<List<GetPortalPageAccessGrantsResponseDto>>> GetPortalPageAccessGrantsAsync(string portalPageAccessGrantsPermissionGroupName)
        {
            return await ExecuteWithExceptionHandling("GetPortalPageAccessGrants", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PortalPageAccessGrant.Query.GetPortalPageAccessGrants);
                var parameters = new
                {
                    PRM_PortalPageAccessGrants_PermissionGroupName = portalPageAccessGrantsPermissionGroupName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetPortalPageAccessGrantsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in PortalPageAccessGrant");
            });
        }

        public async Task<RepoResponse<List<GetPortalPageAccessGrantResponseDto>>> GetPortalPageAccessGrantAsync(string portalPageAccessGrantsPermissionGroupName, string portalPageAccessGrantsPortalPageDefinitionKey, PageActionType portalPageAccessGrantsPageAction)
        {
            return await ExecuteWithExceptionHandling("GetPortalPageAccessGrant", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PortalPageAccessGrant.Query.GetPortalPageAccessGrant);
                var parameters = new
                {
                    PRM_PortalPageAccessGrants_PortalPageDefinitionKey = portalPageAccessGrantsPortalPageDefinitionKey,
                    PRM_PortalPageAccessGrants_PermissionGroupName = portalPageAccessGrantsPermissionGroupName,
                    PRM_PortalPageAccessGrants_PageAction = portalPageAccessGrantsPageAction
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetPortalPageAccessGrantResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in PortalPageAccessGrant");
            });
        }
    }
}