//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo-kahve.ProductionModuleModule.Domain.Enums;
namespace QuickCode.Demo - kahve . ProductionModuleModule . Application . Dtos . ProductionError {
    public record GetByProcessIdResponseDto
    {
        public int Id { get; init; }
        public int ProcessId { get; init; }
        public DateTime ErrorDate { get; init; }
        public string ErrorDescription { get; init; }
        public string ErrorSeverity { get; init; }
    }
}