SELECT [ID], [EQUIPMENT_NAME], [EQUIPMENT_DESCRIPTION] 
FROM [RECIPE_EQUIPMENTS] 
WHERE [IsDeleted] = 0 
	AND [RECIPE_ID] = @PRM_RECIPE_EQUIPMENTS_RECIPE_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 