//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo-kahve.Common.Models; using  QuickCode . Demo
-kahve.IdentityModule.Domain.Entities; using  QuickCode . Demo
-kahve.IdentityModule.Application.Interfaces.Repositories; using  System . Threading . Tasks ;  using  Dapper ;  using  Microsoft . EntityFrameworkCore ;  using  Microsoft . Extensions . Logging ;  using  QuickCode . Demo
-kahve.Common; using  QuickCode . Demo
-kahve.Common.Extensions; using  QuickCode . Demo
-kahve.Common.Helpers; using  QuickCode . Demo
-kahve.IdentityModule.Persistence.Contexts; using  QuickCode . Demo
-kahve.IdentityModule.Application.Dtos.ApiMethodAccessGrant; using  QuickCode . Demo
-kahve.IdentityModule.Application.Mappings; using  QuickCode . Demo
-kahve.IdentityModule.Persistence.Sql; using  QuickCode . Demo
-kahve.IdentityModule.Domain.Enums;
namespace QuickCode.Demo - kahve . IdentityModule . Persistence . Repositories {
    public partial class ApiMethodAccessGrantRepository : BaseRepository, IApiMethodAccessGrantRepository
    {
        public async Task<RepoResponse<List<GetApiMethodAccessGrantNamesResponseDto>>> GetApiMethodAccessGrantNamesAsync(string apiMethodAccessGrantsPermissionGroupName)
        {
            return await ExecuteWithExceptionHandling("GetApiMethodAccessGrantNames", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ApiMethodAccessGrant.Query.GetApiMethodAccessGrantNames);
                var parameters = new
                {
                    PRM_ApiMethodAccessGrants_PermissionGroupName = apiMethodAccessGrantsPermissionGroupName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetApiMethodAccessGrantNamesResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in ApiMethodAccessGrant");
            });
        }
    }
}