SELECT [ID], [CATEGORY_NAME], [DESCRIPTION] 
FROM [RECIPE_CATEGORIES] 
WHERE [IsDeleted] = 0 
	AND [IS_ACTIVE] = @PRM_RECIPE_CATEGORIES_IS_ACTIVE 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 