SELECT RC.[ID], RC.[CATEGORY_NAME], RC.[DESCRIPTION], RC.[IS_ACTIVE] 
FROM [RECIPE_CATEGORY_ASSIGNMENTS] RCA 
	INNER JOIN [RECIPE_CATEGORIES] RC 
			ON RCA.[CATEGORY_ID] = RC.[ID] 
WHERE RCA.[IsDeleted] = 0 
	AND RC.[IsDeleted] = 0 
	AND RC.[ID] = @PRM_RECIPE_CATEGORIES_ID 
ORDER BY RC.[ID] 