SELECT RCA.[ID], RCA.[RECIPE_ID], RCA.[CATEGORY_ID] 
FROM [RECIPE_CATEGORY_ASSIGNMENTS] RCA 
	INNER JOIN [RECIPE_CATEGORIES] RC 
			ON RCA.[CATEGORY_ID] = RC.[ID] 
WHERE RCA.[IsDeleted] = 0 
	AND RC.[IsDeleted] = 0 
	AND RCA.[ID] = @PRM_RECIPE_CATEGORY_ASSIGNMENTS_ID 
	AND RC.[ID] = @PRM_RECIPE_CATEGORIES_ID 
ORDER BY RCA.[ID] 