//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo-kahve.Common.Models; using  QuickCode . Demo
-kahve.RecipeModuleModule.Domain.Entities; using  QuickCode . Demo
-kahve.RecipeModuleModule.Application.Interfaces.Repositories; using  System . Threading . Tasks ;  using  Dapper ;  using  Microsoft . EntityFrameworkCore ;  using  Microsoft . Extensions . Logging ;  using  QuickCode . Demo
-kahve.Common; using  QuickCode . Demo
-kahve.Common.Extensions; using  QuickCode . Demo
-kahve.RecipeModuleModule.Persistence.Contexts; using  QuickCode . Demo
-kahve.RecipeModuleModule.Application.Dtos.RecipeCategoryAssignment; using  QuickCode . Demo
-kahve.RecipeModuleModule.Application.Mappings;
namespace QuickCode.Demo - kahve . RecipeModuleModule . Persistence . Repositories {
    public partial class RecipeCategoryAssignmentRepository : BaseRepository, IRecipeCategoryAssignmentRepository
    {
        private readonly WriteDbContext _writeContext;
        private readonly ReadDbContext _readContext;
        public RecipeCategoryAssignmentRepository(ILogger<RecipeCategoryAssignmentRepository> logger, WriteDbContext writeContext, ReadDbContext readContext) : base(logger, "RecipeCategoryAssignment")
        {
            _writeContext = writeContext;
            _readContext = readContext;
        }

        public async Task<RepoResponse<RecipeCategoryAssignmentDto>> InsertAsync(RecipeCategoryAssignmentDto value)
        {
            return await ExecuteWithExceptionHandling("Insert", async () =>
            {
                var entity = value.ToEntity();
                await _writeContext.RecipeCategoryAssignment.AddAsync(entity);
                await _writeContext.SaveChangesAsync();
                var resultDto = entity.ToDto();
                return new RepoResponse<RecipeCategoryAssignmentDto>(resultDto, "Success");
            });
        }

        public async Task<RepoResponse<bool>> UpdateAsync(RecipeCategoryAssignmentDto value)
        {
            return await ExecuteWithExceptionHandling("Update", async () =>
            {
                _writeContext.Set<Domain.Entities.RecipeCategoryAssignment>().Update(value.ToEntity());
                await _writeContext.SaveChangesAsync();
                return new RepoResponse<bool>(true, "Success");
            });
        }

        public async Task<RepoResponse<bool>> DeleteAsync(RecipeCategoryAssignmentDto value)
        {
            return await ExecuteWithExceptionHandling("Delete", async () =>
            {
                _writeContext.RecipeCategoryAssignment.Remove(value.ToEntity());
                await _writeContext.SaveChangesAsync();
                return new RepoResponse<bool>(true, "Success");
            });
        }

        public async Task<RepoResponse<RecipeCategoryAssignmentDto>> GetByPkAsync(int id)
        {
            return await ExecuteWithExceptionHandling("GetByPk", async () =>
            {
                var result =
                    from recipe_category_assignment in _readContext.RecipeCategoryAssignment
                    where recipe_category_assignment.Id.Equals(id)
                    select recipe_category_assignment;
                var response = await result.FirstOrDefaultAsync();
                return response == null ? new RepoResponse<RecipeCategoryAssignmentDto>
                {
                    Code = 404,
                    Message = "Not found in RecipeCategoryAssignment"
                }

                : new RepoResponse<RecipeCategoryAssignmentDto>(response.ToDto(), "Success");
            });
        }

        public async Task<RepoResponse<List<RecipeCategoryAssignmentDto>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            return await ExecuteWithExceptionHandling("Select", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<RecipeCategoryAssignmentDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }

                var query = _readContext.RecipeCategoryAssignment.OrderBy(o => o.Id).AsQueryable();
                if (pageNumber.HasValue && pageSize.HasValue)
                {
                    query = ApplyPagination(query, pageNumber.Value, pageSize.Value);
                }

                var result = await query.ToListAsync();
                return new RepoResponse<List<RecipeCategoryAssignmentDto>>(result.ToDto(), "Success");
            });
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            return await ExecuteWithExceptionHandling("Count", async () =>
            {
                return new RepoResponse<int>(await _readContext.RecipeCategoryAssignment.CountAsync(), "Success");
            });
        }
    }
}