SELECT [ID], [INGREDIENT_NAME], [QUANTITY], [UNIT] 
FROM [RECIPE_INGREDIENTS] 
WHERE [IsDeleted] = 0 
	AND [RECIPE_ID] = @PRM_RECIPE_INGREDIENTS_RECIPE_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 