//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo-kahve.ProductionModuleModule.Domain.Enums;
namespace QuickCode.Demo - kahve . ProductionModuleModule . Application . Dtos . RoastingProcess {
    public record GetByBeanBatchIdResponseDto
    {
        public int Id { get; init; }
        public int BeanBatchId { get; init; }
        public DateTime RoastingDate { get; init; }
        public int TemperatureCelsius { get; init; }
        public int DurationMinutes { get; init; }
        public ProcessStatus ProcessStatus { get; init; }
    }
}