//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo-kahve.ProductionModuleModule.Domain.Enums;
namespace QuickCode.Demo - kahve . ProductionModuleModule . Application . Dtos . ProcessEquipment {
    public record ProcessEquipmentDto
    {
        public int Id { get; init; }
        public string EquipmentName { get; init; }
        public string EquipmentType { get; init; }
        public DateTime LastMaintenanceDate { get; init; }
        public bool IsActive { get; init; }
        public DateTime CreatedDate { get; init; }
    }
}