//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.Demo-kahve.Portal.Models; using  QuickCode . Demo
-kahve.Portal.Models.ProductionModuleModule; using  QuickCode . Demo
-kahve.Portal.Helpers; using  Microsoft . AspNetCore . Mvc ;  using  IdentityModuleContracts  =  QuickCode . Demo
-kahve.Common.Nswag.Clients.IdentityModuleApi.Contracts; using  ProductionModuleModuleContracts  =  QuickCode . Demo
-kahve.Common.Nswag.Clients.ProductionModuleModuleApi.Contracts; using  System . IO ;  using  Microsoft . AspNetCore . Authorization ;  using  QuickCode . Demo
-kahve.Portal.Helpers.Authorization; using  Microsoft . AspNetCore . Http ;  using  System . Threading ;  using  System . Threading . Tasks ;  using  AutoRest . Core . Utilities . Collections ;  using  Microsoft . Extensions . Caching . Memory ;  using  Microsoft . AspNetCore . Mvc . Rendering ; 
namespace QuickCode.Demo - kahve . Portal . Controllers . ProductionModuleModule {
    [Permission("ProductionModuleModulePackagingProcesses")]
    [Area("ProductionModuleModule")]
    [Route("ProductionModuleModulePackagingProcesses")]
    public partial class PackagingProcessesController : BaseController
    {
        private readonly ProductionModuleModuleContracts.IPackagingProcessesClient pageClient;
        private readonly ProductionModuleModuleContracts.IGrindingProcessesClient pageGrindingProcessClient;
        public PackagingProcessesController(ProductionModuleModuleContracts.IPackagingProcessesClient pageClient, ProductionModuleModuleContracts.IGrindingProcessesClient pageGrindingProcessClient, IdentityModuleContracts.ITableComboboxSettingsClient tableComboboxSettingsClient, IHttpContextAccessor httpContextAccessor, IMemoryCache cache) : base(tableComboboxSettingsClient, httpContextAccessor, cache)
        {
            this.pageClient = pageClient;
            this.pageGrindingProcessClient = pageGrindingProcessClient;
        }

        [ResponseCache(VaryByQueryKeys = new[] { "ic" }, Duration = 30)]
        public async Task<IActionResult> GetImage(string ic)
        {
            return await GetImageResult(pageClient, ic);
        }

        [Route("List")]
        public async Task<IActionResult> List()
        {
            var model = await PrepareModel();
            model.ComboList = await FillPageComboBoxes(model.ComboList);
            SetModelBinder(ref model);
            return View("List", model);
        }

        [Route("List")]
        [HttpPost]
        public async Task<IActionResult> List(PackagingProcessData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = new();
            SetModelBinder(ref model);
            return View("List", model);
        }

        [Route("Insert")]
        [HttpPost]
        public async Task<IActionResult> Insert(PackagingProcessData model)
        {
            ModelBinder(ref model);
            var result = await pageClient.PackagingProcessesInsertAsync(model.SelectedItem);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("Update")]
        [HttpPost]
        public async Task<IActionResult> Update(PackagingProcessData model)
        {
            ModelBinder(ref model);
            var request = model.SelectedItem;
            var result = await pageClient.PackagingProcessesUpdateAsync(request.Id, request);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("Delete")]
        [HttpPost]
        public async Task<IActionResult> Delete(PackagingProcessData model)
        {
            ModelBinder(ref model);
            var request = model.SelectedItem;
            var result = await pageClient.PackagingProcessesDeleteAsync(request.Id);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("InsertItem")]
        public IActionResult InsertItem(PackagingProcessData model)
        {
            ModelState.Clear();
            ModelBinder(ref model);
            SetModelBinder(ref model);
            model.SelectedItem = new();
            return PartialView("Insert", model);
        }

        [Route("DetailItem")]
        public async Task<IActionResult> DetailItem(PackagingProcessData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Detail", model);
        }

        [Route("UpdateItem")]
        [HttpPost]
        public async Task<IActionResult> UpdateItem(PackagingProcessData model)
        {
            ModelState.Clear();
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Update", model);
        }

        [Route("DeleteItem")]
        [HttpPost]
        public async Task<IActionResult> DeleteItem(PackagingProcessData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Delete", model);
        }

        private async Task<PackagingProcessData> PrepareModel()
        {
            var model = GetModel<PackagingProcessData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            return await PrepareModel(model);
        }

        private async Task<PackagingProcessData> PrepareModel(PackagingProcessData model)
        {
            model.NumberOfRecord = await pageClient.PackagingProcessesCountAsync();
            model.TotalPage = (model.NumberOfRecord + PageSize - 1) / PageSize;
            model.List = (await pageClient.PackagingProcessesListAsync(model.CurrentPage, PageSize)).ToList();
            return model;
        }

        private async Task<Dictionary<string, Dictionary<string, string>>> FillPageComboBoxes(Dictionary<string, Dictionary<string, string>> comboBoxList)
        {
            comboBoxList.Clear();
            comboBoxList.AddRange(await FillComboBoxAsync("GrindingProcesses", () => pageGrindingProcessClient.GrindingProcessesListAsync()));
            return comboBoxList;
        }
    }
}