//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.Demo-kahve.Portal.Models; using  QuickCode . Demo
-kahve.Portal.Models.ProductionModuleModule; using  QuickCode . Demo
-kahve.Portal.Helpers; using  Microsoft . AspNetCore . Mvc ;  using  IdentityModuleContracts  =  QuickCode . Demo
-kahve.Common.Nswag.Clients.IdentityModuleApi.Contracts; using  ProductionModuleModuleContracts  =  QuickCode . Demo
-kahve.Common.Nswag.Clients.ProductionModuleModuleApi.Contracts; using  System . IO ;  using  Microsoft . AspNetCore . Authorization ;  using  QuickCode . Demo
-kahve.Portal.Helpers.Authorization; using  Microsoft . AspNetCore . Http ;  using  System . Threading ;  using  System . Threading . Tasks ;  using  AutoRest . Core . Utilities . Collections ;  using  Microsoft . Extensions . Caching . Memory ;  using  Microsoft . AspNetCore . Mvc . Rendering ; 
namespace QuickCode.Demo - kahve . Portal . Controllers . ProductionModuleModule {
    [Permission("ProductionModuleModuleRoastingProcesses")]
    [Area("ProductionModuleModule")]
    [Route("ProductionModuleModuleRoastingProcesses")]
    public partial class RoastingProcessesController : BaseController
    {
        private readonly ProductionModuleModuleContracts.IRoastingProcessesClient pageClient;
        private readonly ProductionModuleModuleContracts.ICoffeeBeansClient pageCoffeeBeanClient;
        public RoastingProcessesController(ProductionModuleModuleContracts.IRoastingProcessesClient pageClient, ProductionModuleModuleContracts.ICoffeeBeansClient pageCoffeeBeanClient, IdentityModuleContracts.ITableComboboxSettingsClient tableComboboxSettingsClient, IHttpContextAccessor httpContextAccessor, IMemoryCache cache) : base(tableComboboxSettingsClient, httpContextAccessor, cache)
        {
            this.pageClient = pageClient;
            this.pageCoffeeBeanClient = pageCoffeeBeanClient;
        }

        [ResponseCache(VaryByQueryKeys = new[] { "ic" }, Duration = 30)]
        public async Task<IActionResult> GetImage(string ic)
        {
            return await GetImageResult(pageClient, ic);
        }

        [Route("List")]
        public async Task<IActionResult> List()
        {
            var model = await PrepareModel();
            model.ComboList = await FillPageComboBoxes(model.ComboList);
            SetModelBinder(ref model);
            return View("List", model);
        }

        [Route("List")]
        [HttpPost]
        public async Task<IActionResult> List(RoastingProcessData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = new();
            SetModelBinder(ref model);
            return View("List", model);
        }

        [Route("Insert")]
        [HttpPost]
        public async Task<IActionResult> Insert(RoastingProcessData model)
        {
            ModelBinder(ref model);
            var result = await pageClient.RoastingProcessesInsertAsync(model.SelectedItem);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("Update")]
        [HttpPost]
        public async Task<IActionResult> Update(RoastingProcessData model)
        {
            ModelBinder(ref model);
            var request = model.SelectedItem;
            var result = await pageClient.RoastingProcessesUpdateAsync(request.Id, request);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("Delete")]
        [HttpPost]
        public async Task<IActionResult> Delete(RoastingProcessData model)
        {
            ModelBinder(ref model);
            var request = model.SelectedItem;
            var result = await pageClient.RoastingProcessesDeleteAsync(request.Id);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("InsertItem")]
        public IActionResult InsertItem(RoastingProcessData model)
        {
            ModelState.Clear();
            ModelBinder(ref model);
            SetModelBinder(ref model);
            model.SelectedItem = new();
            return PartialView("Insert", model);
        }

        [Route("DetailItem")]
        public async Task<IActionResult> DetailItem(RoastingProcessData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Detail", model);
        }

        [Route("UpdateItem")]
        [HttpPost]
        public async Task<IActionResult> UpdateItem(RoastingProcessData model)
        {
            ModelState.Clear();
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Update", model);
        }

        [Route("DeleteItem")]
        [HttpPost]
        public async Task<IActionResult> DeleteItem(RoastingProcessData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Delete", model);
        }

        private async Task<RoastingProcessData> PrepareModel()
        {
            var model = GetModel<RoastingProcessData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            return await PrepareModel(model);
        }

        private async Task<RoastingProcessData> PrepareModel(RoastingProcessData model)
        {
            model.NumberOfRecord = await pageClient.RoastingProcessesCountAsync();
            model.TotalPage = (model.NumberOfRecord + PageSize - 1) / PageSize;
            model.List = (await pageClient.RoastingProcessesListAsync(model.CurrentPage, PageSize)).ToList();
            return model;
        }

        private async Task<Dictionary<string, Dictionary<string, string>>> FillPageComboBoxes(Dictionary<string, Dictionary<string, string>> comboBoxList)
        {
            comboBoxList.Clear();
            comboBoxList.AddRange(await FillComboBoxAsync("CoffeeBeans", () => pageCoffeeBeanClient.CoffeeBeansListAsync()));
            return comboBoxList;
        }
    }
}