SELECT [ID], [PROCESS_ID], [ERROR_DATE], [ERROR_DESCRIPTION], [ERROR_SEVERITY] 
FROM [PRODUCTION_ERRORS] 
WHERE [IsDeleted] = 0 
	AND [PROCESS_ID] = @PRM_PRODUCTION_ERRORS_PROCESS_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 