SELECT [ID], [BATCH_ID], [ORIGIN], [WEIGHT_KG], [ARRIVAL_DATE] 
FROM [COFFEE_BEANS] 
WHERE [IsDeleted] = 0 
	AND [BATCH_ID] = @PRM_COFFEE_BEANS_BATCH_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 