SELECT CB.[ID], CB.[BATCH_ID], CB.[ORIGIN], CB.[WEIGHT_KG], CB.[ARRIVAL_DATE], CB.[IS_ACTIVE], CB.[CREATED_DATE] 
FROM [ROASTING_PROCESSES] RP 
	INNER JOIN [COFFEE_BEANS] CB 
			ON RP.[BEAN_BATCH_ID] = CB.[ID] 
WHERE RP.[IsDeleted] = 0 
	AND CB.[IsDeleted] = 0 
	AND CB.[ID] = @PRM_COFFEE_BEANS_ID 
ORDER BY CB.[ID] 