SELECT RP.[ID], RP.[BEAN_BATCH_ID], RP.[ROASTING_DATE], RP.[TEMPERATURE_CELSIUS], RP.[DURATION_MINUTES], RP.[PROCESS_STATUS], RP.[CREATED_DATE] 
FROM [ROASTING_PROCESSES] RP 
	INNER JOIN [COFFEE_BEANS] CB 
			ON RP.[BEAN_BATCH_ID] = CB.[ID] 
WHERE RP.[IsDeleted] = 0 
	AND CB.[IsDeleted] = 0 
	AND RP.[ID] = @PRM_ROASTING_PROCESSES_ID 
	AND CB.[ID] = @PRM_COFFEE_BEANS_ID 
ORDER BY RP.[ID] 