//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.Demo-kahve.Portal.Models; using  QuickCode . Demo
-kahve.Portal.Models.RecipeModuleModule; using  QuickCode . Demo
-kahve.Portal.Helpers; using  Microsoft . AspNetCore . Mvc ;  using  IdentityModuleContracts  =  QuickCode . Demo
-kahve.Common.Nswag.Clients.IdentityModuleApi.Contracts; using  RecipeModuleModuleContracts  =  QuickCode . Demo
-kahve.Common.Nswag.Clients.RecipeModuleModuleApi.Contracts; using  System . IO ;  using  Microsoft . AspNetCore . Authorization ;  using  QuickCode . Demo
-kahve.Portal.Helpers.Authorization; using  Microsoft . AspNetCore . Http ;  using  System . Threading ;  using  System . Threading . Tasks ;  using  AutoRest . Core . Utilities . Collections ;  using  Microsoft . Extensions . Caching . Memory ;  using  Microsoft . AspNetCore . Mvc . Rendering ; 
namespace QuickCode.Demo - kahve . Portal . Controllers . RecipeModuleModule {
    [Permission("RecipeModuleModuleRecipeCategories")]
    [Area("RecipeModuleModule")]
    [Route("RecipeModuleModuleRecipeCategories")]
    public partial class RecipeCategoriesController : BaseController
    {
        private readonly RecipeModuleModuleContracts.IRecipeCategoriesClient pageClient;
        public RecipeCategoriesController(RecipeModuleModuleContracts.IRecipeCategoriesClient pageClient, IdentityModuleContracts.ITableComboboxSettingsClient tableComboboxSettingsClient, IHttpContextAccessor httpContextAccessor, IMemoryCache cache) : base(tableComboboxSettingsClient, httpContextAccessor, cache)
        {
            this.pageClient = pageClient;
        }

        [ResponseCache(VaryByQueryKeys = new[] { "ic" }, Duration = 30)]
        public async Task<IActionResult> GetImage(string ic)
        {
            return await GetImageResult(pageClient, ic);
        }

        [Route("List")]
        public async Task<IActionResult> List()
        {
            var model = await PrepareModel();
            SetModelBinder(ref model);
            return View("List", model);
        }

        [Route("List")]
        [HttpPost]
        public async Task<IActionResult> List(RecipeCategoryData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = new();
            SetModelBinder(ref model);
            return View("List", model);
        }

        [Route("Insert")]
        [HttpPost]
        public async Task<IActionResult> Insert(RecipeCategoryData model)
        {
            ModelBinder(ref model);
            var result = await pageClient.RecipeCategoriesInsertAsync(model.SelectedItem);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("Update")]
        [HttpPost]
        public async Task<IActionResult> Update(RecipeCategoryData model)
        {
            ModelBinder(ref model);
            var request = model.SelectedItem;
            var result = await pageClient.RecipeCategoriesUpdateAsync(request.Id, request);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("Delete")]
        [HttpPost]
        public async Task<IActionResult> Delete(RecipeCategoryData model)
        {
            ModelBinder(ref model);
            var request = model.SelectedItem;
            var result = await pageClient.RecipeCategoriesDeleteAsync(request.Id);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("InsertItem")]
        public IActionResult InsertItem(RecipeCategoryData model)
        {
            ModelState.Clear();
            ModelBinder(ref model);
            SetModelBinder(ref model);
            model.SelectedItem = new();
            return PartialView("Insert", model);
        }

        [Route("DetailItem")]
        public async Task<IActionResult> DetailItem(RecipeCategoryData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Detail", model);
        }

        [Route("UpdateItem")]
        [HttpPost]
        public async Task<IActionResult> UpdateItem(RecipeCategoryData model)
        {
            ModelState.Clear();
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Update", model);
        }

        [Route("DeleteItem")]
        [HttpPost]
        public async Task<IActionResult> DeleteItem(RecipeCategoryData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Delete", model);
        }

        private async Task<RecipeCategoryData> PrepareModel()
        {
            var model = GetModel<RecipeCategoryData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            return await PrepareModel(model);
        }

        private async Task<RecipeCategoryData> PrepareModel(RecipeCategoryData model)
        {
            model.NumberOfRecord = await pageClient.RecipeCategoriesCountAsync();
            model.TotalPage = (model.NumberOfRecord + PageSize - 1) / PageSize;
            model.List = (await pageClient.RecipeCategoriesListAsync(model.CurrentPage, PageSize)).ToList();
            return model;
        }
    }
}