//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo-kahve.IdentityModule.Application.Dtos.KafkaEvent; using  QuickCode . Demo
-kahve.IdentityModule.Domain.Entities; using  QuickCode . Demo
-kahve.IdentityModule.Domain.Enums;
namespace QuickCode.Demo - kahve . IdentityModule . Application . Mappings {
    public static class KafkaEventMappings
    {
        public static List<KafkaEventDto> ToDto(this IEnumerable<KafkaEvent> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static KafkaEventDto ToDto(this KafkaEvent model)
        {
            return new KafkaEventDto
            {
                TopicName = model.TopicName,
                ApiMethodDefinitionKey = model.ApiMethodDefinitionKey,
                IsActive = model.IsActive
            };
        }

        public static KafkaEvent ToEntity(this KafkaEventDto model)
        {
            return new KafkaEvent
            {
                TopicName = model.TopicName,
                ApiMethodDefinitionKey = model.ApiMethodDefinitionKey,
                IsActive = model.IsActive
            };
        }
    }
}