//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demo-kahve.IdentityModule.Application.Dtos.PermissionGroup; using  QuickCode . Demo
-kahve.IdentityModule.Domain.Entities; using  QuickCode . Demo
-kahve.IdentityModule.Domain.Enums;
namespace QuickCode.Demo - kahve . IdentityModule . Application . Mappings {
    public static class PermissionGroupMappings
    {
        public static List<PermissionGroupDto> ToDto(this IEnumerable<PermissionGroup> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static PermissionGroupDto ToDto(this PermissionGroup model)
        {
            return new PermissionGroupDto
            {
                Name = model.Name,
                Description = model.Description
            };
        }

        public static PermissionGroup ToEntity(this PermissionGroupDto model)
        {
            return new PermissionGroup
            {
                Name = model.Name,
                Description = model.Description
            };
        }
    }
}