//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demo-kahve.Common.Models; using  QuickCode . Demo
-kahve.RecipeModuleModule.Domain.Entities; using  QuickCode . Demo
-kahve.RecipeModuleModule.Application.Interfaces.Repositories; using  System . Threading . Tasks ;  using  Dapper ;  using  Microsoft . EntityFrameworkCore ;  using  Microsoft . Extensions . Logging ;  using  QuickCode . Demo
-kahve.Common; using  QuickCode . Demo
-kahve.Common.Extensions; using  QuickCode . Demo
-kahve.Common.Helpers; using  QuickCode . Demo
-kahve.RecipeModuleModule.Persistence.Contexts; using  QuickCode . Demo
-kahve.RecipeModuleModule.Application.Dtos.Recipe; using  QuickCode . Demo
-kahve.RecipeModuleModule.Application.Mappings; using  QuickCode . Demo
-kahve.RecipeModuleModule.Persistence.Sql;
namespace QuickCode.Demo - kahve . RecipeModuleModule . Persistence . Repositories {
    public partial class RecipeRepository : BaseRepository, IRecipeRepository
    {
        public async Task<RepoResponse<List<GetActiveResponseDto>>> GetActiveAsync(bool recipesIsActive, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetActive", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetActiveResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Recipe.Query.GetActive);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_RECIPES_IS_ACTIVE = recipesIsActive,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetActiveResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Recipe");
                }
            });
        }

        public async Task<RepoResponse<List<SearchByNameResponseDto>>> SearchByNameAsync(string recipesRecipeName, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("SearchByName", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<SearchByNameResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Recipe.Query.SearchByName);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_RECIPES_RECIPE_NAME = recipesRecipeName,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<SearchByNameResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Recipe");
                }
            });
        }

        public async Task<RepoResponse<List<GetRecipeIngredientsForRecipesResponseDto>>> GetRecipeIngredientsForRecipesAsync(int recipesId)
        {
            return await ExecuteWithExceptionHandling("GetRecipeIngredientsForRecipes", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Recipe.Query.GetRecipeIngredientsForRecipes);
                var parameters = new
                {
                    PRM_RECIPES_ID = recipesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetRecipeIngredientsForRecipesResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in Recipe");
            });
        }

        public async Task<RepoResponse<GetRecipeIngredientsForRecipesResponseDto>> GetRecipeIngredientsForRecipesDetailsAsync(int recipesId, int recipeIngredientsId)
        {
            return await ExecuteWithExceptionHandling("GetRecipeIngredientsForRecipesDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Recipe.Query.GetRecipeIngredientsForRecipesDetails);
                var parameters = new
                {
                    PRM_RECIPE_INGREDIENTS_ID = recipeIngredientsId,
                    PRM_RECIPES_ID = recipesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetRecipeIngredientsForRecipesResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Recipe");
            });
        }

        public async Task<RepoResponse<List<GetRecipeEquipmentsForRecipesResponseDto>>> GetRecipeEquipmentsForRecipesAsync(int recipesId)
        {
            return await ExecuteWithExceptionHandling("GetRecipeEquipmentsForRecipes", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Recipe.Query.GetRecipeEquipmentsForRecipes);
                var parameters = new
                {
                    PRM_RECIPES_ID = recipesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetRecipeEquipmentsForRecipesResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in Recipe");
            });
        }

        public async Task<RepoResponse<GetRecipeEquipmentsForRecipesResponseDto>> GetRecipeEquipmentsForRecipesDetailsAsync(int recipesId, int recipeEquipmentsId)
        {
            return await ExecuteWithExceptionHandling("GetRecipeEquipmentsForRecipesDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Recipe.Query.GetRecipeEquipmentsForRecipesDetails);
                var parameters = new
                {
                    PRM_RECIPE_EQUIPMENTS_ID = recipeEquipmentsId,
                    PRM_RECIPES_ID = recipesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetRecipeEquipmentsForRecipesResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Recipe");
            });
        }

        public async Task<RepoResponse<List<GetRecipeNotesForRecipesResponseDto>>> GetRecipeNotesForRecipesAsync(int recipesId)
        {
            return await ExecuteWithExceptionHandling("GetRecipeNotesForRecipes", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Recipe.Query.GetRecipeNotesForRecipes);
                var parameters = new
                {
                    PRM_RECIPES_ID = recipesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetRecipeNotesForRecipesResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in Recipe");
            });
        }

        public async Task<RepoResponse<GetRecipeNotesForRecipesResponseDto>> GetRecipeNotesForRecipesDetailsAsync(int recipesId, int recipeNotesId)
        {
            return await ExecuteWithExceptionHandling("GetRecipeNotesForRecipesDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Recipe.Query.GetRecipeNotesForRecipesDetails);
                var parameters = new
                {
                    PRM_RECIPE_NOTES_ID = recipeNotesId,
                    PRM_RECIPES_ID = recipesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetRecipeNotesForRecipesResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Recipe");
            });
        }

        public async Task<RepoResponse<List<GetRecipeImagesForRecipesResponseDto>>> GetRecipeImagesForRecipesAsync(int recipesId)
        {
            return await ExecuteWithExceptionHandling("GetRecipeImagesForRecipes", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Recipe.Query.GetRecipeImagesForRecipes);
                var parameters = new
                {
                    PRM_RECIPES_ID = recipesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetRecipeImagesForRecipesResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in Recipe");
            });
        }

        public async Task<RepoResponse<GetRecipeImagesForRecipesResponseDto>> GetRecipeImagesForRecipesDetailsAsync(int recipesId, int recipeImagesId)
        {
            return await ExecuteWithExceptionHandling("GetRecipeImagesForRecipesDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Recipe.Query.GetRecipeImagesForRecipesDetails);
                var parameters = new
                {
                    PRM_RECIPE_IMAGES_ID = recipeImagesId,
                    PRM_RECIPES_ID = recipesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetRecipeImagesForRecipesResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Recipe");
            });
        }

        public async Task<RepoResponse<List<GetRecipeCategoryAssignmentsForRecipesResponseDto>>> GetRecipeCategoryAssignmentsForRecipesAsync(int recipesId)
        {
            return await ExecuteWithExceptionHandling("GetRecipeCategoryAssignmentsForRecipes", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Recipe.Query.GetRecipeCategoryAssignmentsForRecipes);
                var parameters = new
                {
                    PRM_RECIPES_ID = recipesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetRecipeCategoryAssignmentsForRecipesResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in Recipe");
            });
        }

        public async Task<RepoResponse<GetRecipeCategoryAssignmentsForRecipesResponseDto>> GetRecipeCategoryAssignmentsForRecipesDetailsAsync(int recipesId, int recipeCategoryAssignmentsId)
        {
            return await ExecuteWithExceptionHandling("GetRecipeCategoryAssignmentsForRecipesDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Recipe.Query.GetRecipeCategoryAssignmentsForRecipesDetails);
                var parameters = new
                {
                    PRM_RECIPE_CATEGORY_ASSIGNMENTS_ID = recipeCategoryAssignmentsId,
                    PRM_RECIPES_ID = recipesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetRecipeCategoryAssignmentsForRecipesResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Recipe");
            });
        }
    }
}